### ISSUE TITLE
fiddler everywhere 4.01  on m2 Mac无限加载

### ISSUE THREAD

**Issue by Svring** [msojocs/fiddler-everywhere-enhance#19]
3.4版本的破解文件放在mac下4.01版本的fiddler中会导致无限加载，这是在开启试用期并修改文件之后
测试了一下，如果只替换Fiddler.WebUi.dll和FiddlerBackendSDK.dll的话会导致无法登陆，如果只替换main.2e20c4aa11e930e4.js的话会导致闪退，所以问题出在main.2e20c4aa11e930e4.js的可能要大一些
可以请教一下解决方案吗

**Comment by igocc** [comment]
同样的问题，求解决方法。

**Comment by ZengJun-cloud** [comment]
同问

**Comment by aTenb** [comment]
同求M芯片MAC版本,非M芯片用win版本就可以了

**Comment by xumoyan** [comment]
> [Fiddler Everywhere 4.0.1_mac.zip](https://github.com/msojocs/fiddler-everywhere-enhance/files/10409630/Fiddler.Everywhere.4.0.1_mac.zip)
> 
> 试试这个？

4.0.1 替换 !e.settingsService.get().autoUpdateSettings.disabled 禁止了自动更新
替换对应文件，打开一直 please wait

替换你发的这个dll文件闪退

mac m1 求帮助

**Comment by xumoyan** [comment]
解决了

**Comment by pjy612** [comment]
> > [Fiddler Everywhere 4.0.1_mac.zip](https://github.com/msojocs/fiddler-everywhere-enhance/files/10409630/Fiddler.Everywhere.4.0.1_mac.zip)
> > 试试这个？
> 
> 4.0.1 替换 !e.settingsService.get().autoUpdateSettings.disabled 禁止了自动更新 替换对应文件，打开一直 please wait
> 
> 替换你发的这个dll文件闪退
> 
> mac m1 求帮助

闪退是你改了js吧？ 不改js 试试
