### ISSUE TITLE
Please wait

### ISSUE THREAD

**Issue by KaczkiSomSuper** [msojocs/fiddler-everywhere-enhance#20]
Stuck at please wait win 10 4.0.1

**Comment by pjy612** [comment]
[Fiddler Everywhere 4.0.1_win.zip](https://github.com/msojocs/fiddler-everywhere-enhance/files/10409648/Fiddler.Everywhere.4.0.1_win.zip)

try this

**Comment by sudo-angelo** [comment]
> 

problem still persists, even with new dll + changing .js to include "Enterprise" instead of "Pro"

**Comment by pjy612** [comment]
> > 
> 
> problem still persists, even with new dll + changing .js to include "Enterprise" instead of "Pro"

don't change js
