### ISSUE TITLE
Please wait... stuck

### ISSUE THREAD

**Issue by sudo-angelo** [msojocs/fiddler-everywhere-enhance#23]
Here are the steps that I followed:

1. Create a fresh install of Fiddler Everywhere v4.0.1 on Windows 11
2. From `fiddler-everywhere-enhance-master\v4.01 win trial to enterprise`, drag `Fiddler.Webui.dll`, `FiddlerBackend.Contracts.dll`, `FiddlerBackendSDK.dll` into `Fiddler Everywhere\resources\app\out\Webserver`
3. From `fiddler-everywhere-enhance-master\v4.0.1`, drag `main.c5f6cd9850653179.js` into `Fiddler Everywhere\resources\app\out\WebServer\ClientApp\dist`
4. Modify `main.c5f6cd9850653179.js` to change the line containing `"Pro"` to `"Enterprise"`, such that it looks like: `ve.licenseInfo.currentLicense = "Enterprise"`
5. Start Fiddler Everywhere

Doing this will lead me to have the permanent Please wait... screen.

**Comment by pjy612** [comment]
please only use "v4.01 win trial to enterprise"
don't change js
