### ISSUE TITLE
Autoupdate

### ISSUE THREAD

**Issue by duzers** [msojocs/fiddler-everywhere-enhance#24]
Main problem is autoupdate to never version of Fiddler. After next restart Fiddler update to version 4.1.0 from 4.0.1 and crack stop working.
Solution (I didn't read the manual):
file: fiddler/resources/app/out/main.js
search: !e.settingsService.get().autoUpdateSettings.disabled
change: !true||e.settingsService.get().autoUpdateSettings.disabled

**Comment by pjy612** [comment]
#27
