### ISSUE TITLE
4.1.x Fiddler everywhere Add protective shell and obfuscation

### ISSUE THREAD

**Issue by pjy612** [msojocs/fiddler-everywhere-enhance#25]
4.10 Fiddler.WebUi.dll 加壳了...

**Comment by msojocs** [comment]
你确定？
![image](https://user-images.githubusercontent.com/20937135/214553445-9e273f0e-cbc4-4f71-99fc-5082f0d0358d.png)

**Comment by pjy612** [comment]
是加壳了啊。虽然有别的办法，但是它加壳了

**Comment by pjy612** [comment]
![image](https://user-images.githubusercontent.com/4072526/214572855-b5376d0d-2b7a-4a9f-b400-77f74e3298c6.png)

**Comment by msojocs** [comment]
可能是编辑器自带去壳

**Comment by pjy612** [comment]
![image](https://user-images.githubusercontent.com/4072526/214576382-430175ae-fa0e-4e5d-beed-bc4c128f9331.png)
函数体都很怪，要么就是 还有没加壳的版本流出来 囧

**Comment by msojocs** [comment]
无所谓，只要关键点还能动到就行

**Comment by pjy612** [comment]
现在只能从别的地方动手了，Fiddler.WebUi.dll 我这边不知道怎么动了。
而且看了下其他的DLL应该也有加壳版，但是不知道为什么没实装。
有不少_Secure 目录。如果之后实装了 估计就难弄了。

**Comment by msojocs** [comment]
在工具设置里面设置显示隐藏方法就行了。

**Comment by pjy612** [comment]
emmm 没在一个频道上...

**Comment by ly269nva** [comment]
嗯，4.1版本Fiddler.WebUi.dll修改不了的，dnspy打开后只要一重新保存就就报错，instruction is null， 然后程序就运行不起来。。。 倒是另一个dll可以修改。

**Comment by ly269nva** [comment]
我也改了那个文件，不知道我们改的是不是一样的？@pjy612

**Comment by pjy612** [comment]
> 我也改了那个文件，不知道我们改的是不是一样的？@pjy612

你目前能用了吗？4.1.x 就只能改其他DLL了，而且 只有win的 有dll没替换。
其他两个平台的 已经全加壳了。

**Comment by ly269nva** [comment]
界面看起来能用，但是我的还在试用期内，要下周过了试用期才能看到是否真的能用
![图片](https://user-images.githubusercontent.com/31555480/217470243-c2e78cf5-4ad1-4f53-b7be-55f8814a3745.png)
话说你是改的什么代码？

**Comment by pjy612** [comment]
？就改了两个DLL，改了下返回值。你另一个提问里面回复的就是我改的。

**Comment by ly269nva** [comment]
试用版已显示过期，修改版仍可用，欧拉
