### ISSUE TITLE
Mac M1 Pro crash Fix (guide)

### ISSUE THREAD

**Issue by kanabserg** [msojocs/fiddler-everywhere-enhance#26]
Here is what i did:

1. Downloaded and installed https://downloads.getfiddler.com/mac-arm64/Fiddler%20Everywhere%204.0.1.dmg
2. Opened, set an account, applied trial. Fiddler autoupdated to 4.1.0
3. Delete Fiddler, just move to bin. Do not use any other tools.
4. Install Fiddler once again
5. Apply #24: 
    Replace in /Applications/Fiddler Everywhere.app/Contents/Resources/app/out/main.js
    - old value: !e.settingsService.get().autoUpdateSettings.disabled
    - new value: !true||e.settingsService.get().autoUpdateSettings.disabled
7. Copy Fiddler.WebUi.dll and FiddlerBackendSDK.dll from v4.0.1-mac to /Applications/Fiddler Everywhere.app/Contents/Resources/app/out/WebServer
8. Copy main.2e20c4aa11e930e4.js to /Applications/Fiddler Everywhere.app/Contents/Resources/app/out/WebServer/ClientApp/dist
9. Open app and enjoy

Note:
If discovered **Corrupt and cannot be opened.**, do same as in [https://github.com/msojocs/fiddler-everywhere-enhance/issues/8#issuecomment-1303012900](url)

**Comment by ZengJun-cloud** [comment]
莫名奇妙试了半天居然可以了
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/52198079/216569518-bd12409d-7bdf-4fb5-8139-d52b5b39907e.png">
关闭更新还需要修改 electron-settings.json文件
https://github.com/msojocs/fiddler-everywhere-enhance/issues/27
