### ISSUE TITLE
Fiddler everywhere 4.1.0 not support?

### ISSUE THREAD

**Issue by ly269nva** [msojocs/fiddler-everywhere-enhance#28]
how use Fiddler everywhere 4.1.0 for free?

**Comment by ly269nva** [comment]
i use windows , and  can not find Fiddler.WebUi.Helpers in Fiddler.WebUi.Helpers ,
and no Fiddler.WebUi.il files.

**Comment by pjy612** [comment]
try
https://github.com/pjy612/fiddler-everywhere-enhance
