### ISSUE TITLE
Fiddler everywhere 4.1.1 any tut bypass trial

### ISSUE THREAD

**Issue by hungnhqtnh** [msojocs/fiddler-everywhere-enhance#30]
I'm stuck on the latest version 4.1.1 even though I blocked updates from version 4.0.1
Anyone with a good guide can bypass as possible
Many thanks for the help

**Comment by pjy612** [comment]
https://github.com/pjy612/fiddler-everywhere-enhance/tree/master/v4.1.x%20win%20linux%20mac
