### ISSUE TITLE
替换了v4.0.1 win trial to enterprise还是显示Buy Now

### ISSUE THREAD

**Issue by zymgg** [msojocs/fiddler-everywhere-enhance#32]
下载最新4.6.1版本登录后卸载，修改electron-settings.json禁用更新
下载4.0.1版本后关闭Fiddler，然后替换win trial to enterprise下所有文件到Fiddler Everywhere\resources\app\out\WebServer
显示Buy Now
大佬帮帮忙

**Comment by msojocs** [comment]
我不懂你到底用的是什么版本

**Comment by zymgg** [comment]
4.0.1版本

**Comment by zymgg** [comment]
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/48583393/cacf967a-ef3c-4564-8809-16727d0665a4)

**Comment by msojocs** [comment]
暂时没有

**Comment by msojocs** [comment]
v4.6.1已经可用，大概~

**Comment by zymgg** [comment]
好的，谢谢大佬
