### ISSUE TITLE
大佬 4.6.1会自动更新吗

### ISSUE THREAD

**Issue by liuguojun1022** [msojocs/fiddler-everywhere-enhance#33]
大佬 4.6.1会自动更新至最新版本吗  因为我用401的时候 他一直自己更新 重启就更新 重启就更新 要裂开了

**Comment by msojocs** [comment]
理论上不会更新，参考：

https://github.com/msojocs/fiddler-everywhere-enhance/blob/82c129fb13762f498f6d70e83df48dd662196f27/v4.6.1/server/file/api.getfiddler.com/c/NUNHMjIyNkpNMDg4ZjMzMjZlLTk0OWQtNDgwNi1hMTc2LTFlZGY1MWJiOWRhOA%253D%253D/v/4.6.1/p/win/latest.yml

**Comment by liuguojun1022** [comment]
大佬 好像是会更新的 461 会更新到 462 貌似得保持一直是最新版本

**Comment by msojocs** [comment]
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/20937135/332f11cb-e1f6-46bf-bc69-9b6e4dc5e041)
你readme都不认真看

**Comment by liuguojun1022** [comment]
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/52098260/1c98b2f9-a63e-4811-9695-9409581d1e74)
哈 安装目录没有这个文件夹呀 大佬 理解错了吗我

**Comment by msojocs** [comment]
我不打扰你了，你慢慢领会。

**Comment by liuguojun1022** [comment]
呜呜呜 大佬
