### ISSUE TITLE
Please wait...

### ISSUE THREAD

**Issue by duzers** [msojocs/fiddler-everywhere-enhance#36]
I always see "please wait" with 4.6.1, 4.6.2, 4.7.0

**Comment by duzers** [comment]
Where and how can I do this?

**Comment by msojocs** [comment]
> Where and how can I do this?

https://github.com/msojocs/fiddler-everywhere-enhance/tree/master/v4.6.2#5-%E4%BC%AA%E9%80%A0%E6%9C%8D%E5%8A%A1%E5%99%A8

**Comment by duzers** [comment]
> https://github.com/msojocs/fiddler-everywhere-enhance/tree/master/v4.6.2#5-%E4%BC%AA%E9%80%A0%E6%9C%8D%E5%8A%A1%E5%99%A8

OK, but do I have to change part of code, after "v4.6.1/server/index.js 的内容添加到 resources/app/out/main.js 开头"?

**Comment by msojocs** [comment]
> > https://github.com/msojocs/fiddler-everywhere-enhance/tree/master/v4.6.2#5-%E4%BC%AA%E9%80%A0%E6%9C%8D%E5%8A%A1%E5%99%A8
> 
> OK, but do I have to change part of code, after "v4.6.1/server/index.js 的内容添加到 resources/app/out/main.js 开头"?

You can change it if you want, but you must also change the port in "http://localhost:{port}/api...".

**Comment by msojocs** [comment]
> > https://github.com/msojocs/fiddler-everywhere-enhance/tree/master/v4.6.2#5-%E4%BC%AA%E9%80%A0%E6%9C%8D%E5%8A%A1%E5%99%A8
> 
> OK, but do I have to change part of code, after "v4.6.1/server/index.js 的内容添加到 resources/app/out/main.js 开头"?

Yes, you need to replace the official server to local server.

**Comment by duzers** [comment]
I have to ask you about this problem with first computer.
In netcore.log I can see:
...
[2023-10-15 19:27:20:201] [Information] [NETCore] Getting LicenseClient instance.
[2023-10-15 19:27:20:201] [Information] [NETCore] Getting SubscriptionClient instance.
[2023-10-15 19:27:20:202] [Information] [NETCore] Getting NotificationObservable instance.
[2023-10-15 19:27:20:202] [Information] [NETCore] Getting the user info after a new user login.
[2023-10-15 19:28:22:034] [Error] [NETCore] No network connection!
System.Net.Http.HttpRequestException: No Connection could be made because the target machine actively refused it. (192.168.0.10:8888)
....
I wonder, if 192.168.0.10:8888 is correct. This IP is my IPv4 address.

**Comment by msojocs** [comment]
Try to execute command with `telnet 192.168.0.10 8888`.
If the result is like "Could not open connection to the host, on port 8888: Connect failed", it means the port is not opened in 192.168.0.10.
If another computer was worked, you may need to check your firewall.
