### ISSUE TITLE
v4.01 win trial to enterprise过一段时间后启动登录后会自动注销登录

### ISSUE THREAD

**Issue by DaveBoy** [msojocs/fiddler-everywhere-enhance#37]
国庆前还好好的，结果今天试了下，发现两台机子都出现这种情况（两台电脑之前都用过好几次）

具体情况为：打开提示登录，跳转网页登录成功后，应用提示请等待，然后再次自动打开网页，注销登录

使用方法：
下载[v4.01 win trial to enterprise](https://github.com/msojocs/fiddler-everywhere-enhance/tree/master/v4.01%20win%20trial%20to%20enterprise)文件并覆盖
\Fiddler Everywhere\resources\app\out\WebServer\Fiddler.WebUi.dll
\Fiddler Everywhere\resources\app\out\WebServer\FiddlerBackendSDK.dll
\Fiddler Everywhere\resources\app\out\WebServer\FiddlerBackend.Contracts.dll
然后去除更新(修改方法为之前的方法“搜索 e.settingsService.get().autoUpdateSettings.disabled 替换为 true||e.settingsService.get().autoUpdateSettings.disabled”)，修改\Fiddler Everywhere\resources\app\out\main.js

**Comment by msojocs** [comment]
我不管旧版的，自己研究吧

**Comment by DaveBoy** [comment]
好的
