### ISSUE TITLE
4.8

### ISSUE THREAD

**Issue by Coten7** [msojocs/fiddler-everywhere-enhance#38]
4.8 support

**Comment by msojocs** [comment]
maybe this weekend. maybe...

**Comment by zc16607** [comment]
Version 5.0 has been released

**Comment by starxg** [comment]
[Fiddler Everywhere v5.0.0](https://www.telerik.com/support/whats-new/fiddler-everywhere/release-history/fiddler-everywhere-v5.0.0)

**Comment by Dastano** [comment]
Did 5.0 changed a lot?

**Comment by doandat943** [comment]
version 5.0.0 is out now

**Comment by ConcealedBlade** [comment]
Eagerly waiting for 5.0.0.

**Comment by msojocs** [comment]
Hi, version 5.1.0 is supported now.

**Comment by Dastano** [comment]
> Hi, version 5.1.0 is supported now.

Thanks!

Do we still need:

FiddlerBackendSDK.dll  and do we copy it from 4.6.1?

**Comment by Dastano** [comment]
The moment I add the index.js to the main.js I get:

11:06:17.825 > Displaying splash screen.
11:06:17.920 > No matching processes to clean.
11:06:18.003 > Attempting to run server - 3 attempts left.
11:06:18.004 > Trying to start server at port [40988].
11:06:18.108 > Unable to start server process, closed with code: 252
11:06:18.108 > Attempt failed with Application port calculation failed. Contact support..
11:06:18.108 > Attempting to run server - 2 attempts left.
11:06:18.109 > Trying to start server at port [10633].
11:06:18.214 > Unable to start server process, closed with code: 252
11:06:18.214 > Attempt failed with Application port calculation failed. Contact support..
11:06:18.214 > Attempting to run server - 1 attempts left.
11:06:18.215 > Trying to start server at port [23387].
11:06:18.318 > Unable to start server process, closed with code: 252
11:06:18.318 > Attempt failed with Application port calculation failed. Contact support..
11:06:18.318 > Maximum number of attempts reached - quitting application.

**Comment by msojocs** [comment]
> The moment I add the index.js to the main.js I get:
> 
> 11:06:17.825 > Displaying splash screen. 11:06:17.920 > No matching processes to clean. 11:06:18.003 > Attempting to run server - 3 attempts left. 11:06:18.004 > Trying to start server at port [40988]. 11:06:18.108 > Unable to start server process, closed with code: 252 11:06:18.108 > Attempt failed with Application port calculation failed. Contact support.. 11:06:18.108 > Attempting to run server - 2 attempts left. 11:06:18.109 > Trying to start server at port [10633]. 11:06:18.214 > Unable to start server process, closed with code: 252 11:06:18.214 > Attempt failed with Application port calculation failed. Contact support.. 11:06:18.214 > Attempting to run server - 1 attempts left. 11:06:18.215 > Trying to start server at port [23387]. 11:06:18.318 > Unable to start server process, closed with code: 252 11:06:18.318 > Attempt failed with Application port calculation failed. Contact support.. 11:06:18.318 > Maximum number of attempts reached - quitting application.

Sorry, Did you use the latest commit [e65c95d](https://github.com/msojocs/fiddler-everywhere-enhance/commit/e65c95d8a563473e626727ac07d1a8b6a61f5e13)?

The check of main.js file was removed after this comment https://github.com/msojocs/fiddler-everywhere-enhance/issues/38?notification_referrer_id=NT_kwDOAT95r7M4MjAxMDQ5NTAyOjIwOTM3MTM1#issuecomment-1817456250.

**Comment by Dastano** [comment]
Sorry didn't saw you added another fix. Working now :)

**Comment by ConcealedBlade** [comment]
How to use it?

**Comment by Mr-JBHoo** [comment]
> How to use it? After replacing Fiddler.WebUi.dll, Fiddler can't be launched.如何使用它？替换Fiddler.WebUi.dll后，Fiddler无法启动。
There is also a folder named 'file' to the corresponding place and adding the content in the index.js file to the top of the main.js file UnoM3?

**Comment by Mr-JBHoo** [comment]
> How to use it? After replacing Fiddler.WebUi.dll, Fiddler can't be launched.

There is also a folder named 'file' to the corresponding place and adding the content in the index.js file to the top of the main.js file UnoM3?

**Comment by Mr-JBHoo** [comment]
> How to use it? After replacing Fiddler.WebUi.dll, Fiddler can't be launched.

There is also a folder named 'file' to the corresponding place and adding the content in the index.js to the top of the main.js UnoM3?

**Comment by 1821746019** [comment]
Is there somebody encounter this question?
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/107804044/1c477e3e-71db-4c71-aa1d-dbf5583f71ee)

**Comment by 1821746019** [comment]
The fiddler version is v5.1.0. I follow the instructions in readme but got this issue.
