### ISSUE TITLE
Not Working v3.3.0?

### ISSUE THREAD

**Issue by patch13** [msojocs/fiddler-everywhere-enhance#4]
**HI Dev!**

I am experiencing problems in v 3.3.0. i have replaced 3 files but its continuosly loading.
![Screenshot 2022-07-12 202154](https://user-images.githubusercontent.com/108174114/178526243-2f3cfa6a-3eaa-40b3-91e2-49c9862aec42.png)

**Comment by msojocs** [comment]
the files with suffix 'dll' was built on linux platform, so they may not work on other platform;
if you are using other platform, you need to build them by yourself.

**Comment by patch13** [comment]
how i can build for windows @msojocs

**Comment by msojocs** [comment]
> how i can build for windows @msojocs

following the `readme.md`.

**Comment by kies83** [comment]
@BlackRosePetals what do you mean here?

**Comment by BlackRosePetals** [comment]
第一次登陆的时候提示 Unable to perform the operation.Seems like you do not have access to some of the required network resources.Please open the connectivity test page and ensure it loads successfully on your side.   第二次输入账号密码后就进去了。

**Comment by kies83** [comment]
@msojocs could you please tell me how i can build this for windows version?

**Comment by msojocs** [comment]
> @msojocs could you please tell me how i can build this for windows version?

following the `readme.md`.

**Comment by patch13** [comment]
@msojocs is the process same for windows ? how i can merge the dissamble code into dll?

**Comment by msojocs** [comment]
> @msojocs is the process same for windows ? how i can merge the dissamble code into dll?

the command may like the following code.
https://github.com/msojocs/fiddler-everywhere-crack/blob/e1257bb077fd0e178fcafa781bed13b8e3434b11/crack.sh#L15

**Comment by patch13** [comment]
Check This Picures and function existence getBestAccount: tell me here what to do!



![Screenshot 2022-07-16 114445](https://user-images.githubusercontent.com/108174114/179343681-d427b09e-320d-489a-b245-a852358b614d.jpg)
![Screenshot 2022-07-16 114532](https://user-images.githubusercontent.com/108174114/179343685-ff14cb35-8d8a-4ad0-a221-05f2cc9eddb8.jpg)

**Comment by RootEncrypter** [comment]
@msojocs  please guide

**Comment by cabiamdos** [comment]
Hello, How do I open .dll files to write the source code? I have tried jetbrains dotpeek and it doesn't allow me to edit. thanks

**Comment by cabiamdos** [comment]
the command for windows
`ildasm Fiddler.WebUi.dll /out=Fiddler.WebUi.il`

**Comment by cabiamdos** [comment]
To compile il files for windows:
`ilasm Fiddler.WebUi.il /dll /fold /nologo /noautoinherit`

**Comment by cabiamdos** [comment]
ilsam path to add to environment variables: 
`C:\Windows\Microsoft.NET\Framework\v4.0.30319`
