### ISSUE TITLE
How to Patch?

### ISSUE THREAD

**Issue by dljjld** [msojocs/fiddler-everywhere-enhance#40]
How to Patch?
下载Electron https://github.com/electron/electron/releases , 解压到Electron文件夹
复制 Fiddler Everywhere/resources -> Electron/resources
复制 v4.6.1/Fiddler.WebUi/Fiddler.WebUi.dll -> Electron/resources/app/out/WebServer
复制 v4.6.1/FiddlerBackendSDK/FiddlerBackendSDK.dll -> Electron/resources/app/out/WebServer
复制 v4.6.1/server/file -> Electron/resources/app/out/file

1.Why copy to Electron?
2.How to run Electron?
3.Can you write all steps?

**Comment by DaveBoy** [comment]
![图片](https://github.com/msojocs/fiddler-everywhere-enhance/assets/16101638/8903ac61-1831-4913-bf04-e367b0464c89)

这是我在4.6.1上使用的方法
