### ISSUE TITLE
我在学习的时候，把遇到的所有问题总结在了我的博客上

### ISSUE THREAD

**Issue by ourcss** [msojocs/fiddler-everywhere-enhance#42]
这个dell文件在m1芯片上面没有问题。在inter芯片的mac上，有点问题，相关的文件和教程我发在了我的博客上面，以及在安装过程中遇到的各种问题，有需要的小伙伴自提一下吧  https://www.mimiwuqi.com/biji/156288.html
再次感谢作者提供的支持！

**Comment by msojocs** [comment]
4.0.1，方法太古老了。
