### ISSUE TITLE
5.1.0 readme里面的内容麻烦解释一下什么含义，看不懂

### ISSUE THREAD

**Issue by 15330355709** [msojocs/fiddler-everywhere-enhance#43]
`Fiddler.WebUi.dll
286429000616 -> 286429000618
0F1B283627000616 -> 0F1B283627000618
2B05284E186D33 -> 172A284E186D33`

**Comment by msojocs** [comment]
看不懂说明你不适合看。

**Comment by hongyu315** [comment]
没看懂 + 1
