### ISSUE TITLE
Fidder EveryWhere mac破解以后 在打开恢复原状

### ISSUE THREAD

**Issue by Luxy-byte** [msojocs/fiddler-everywhere-enhance#47]
4.0.1 破解以后是可以正常使用，但是在度打开破解状态就失效了，然后试用期恢复成了 10 天，请问怎么破解啊 这个问题。电脑是 mac-m2pro

**Comment by Nanosk07** [comment]
一样的问题 已经不想折腾了 用proxyman了

**Comment by msojocs** [comment]
搞不懂就别搞，本来就不是明面上的东西，我不能弄的太简单。

**Comment by Nanosk07** [comment]
> 搞不懂就别搞，本来就不是明面上的东西，我不能弄的太简单。

按着步骤来的都没啥问题，只是不生效而已，再加上mac上没有那些工具。有替代品就先用着了，实在没有再想办法

**Comment by msojocs** [comment]
> > 搞不懂就别搞，本来就不是明面上的东西，我不能弄的太简单。
> 
> 按着步骤来的都没啥问题，只是不生效而已，再加上mac上没有那些工具。有替代品就先用着了，实在没有再想办法

mac我没办法，我没mac电脑，测试不了（

**Comment by Luxy-byte** [comment]
我看了哈· 只要联网 mac fidder 就会初始化，代码没有办法组织它登录的时候初始化，所以就会重置并且恢复原状。还是谢谢开源大佬，有空了研究下，谢谢了

**Comment by Luxy-byte** [comment]
> > > 搞不懂就别搞，本来就不是明面上的东西，我不能弄的太简单。
> > 
> > 
> > 按着步骤来的都没啥问题，只是不生效而已，再加上mac上没有那些工具。有替代品就先用着了，实在没有再想办法
> 
> mac我没办法，我没mac电脑，测试不了（

我看了哈· 只要 mac 重启 fidder 在登录账号密码的时候 就会验证 fidder。然后就会重置那个破解文件，就失效了。但是没有办法绕开进去 app 登录账号密码。还是感谢大佬的免费开源

**Comment by msojocs** [comment]
v5.8.1是不需要登录账号的，理论上断网也能用

**Comment by msojocs** [comment]
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/20937135/867bb8a7-bf66-4c2f-8c87-7aeedb4996a1)
刚试了，能离线。

mac自动替换的情况我在windows下没遇到过，不知道什么情况。
