### ISSUE TITLE
Patch usage error

### ISSUE THREAD

**Issue by 3Artem3** [msojocs/fiddler-everywhere-enhance#48]
Hello today. The trial version of the program has expired (10 days), I cannot pay for using the program. And I don't use it on a regular basis. But I would like to be able to use it.

I tried to replace files using your repository, but ended up checking the integrity of the files. And the instructions are not entirely clear what needs to be done.

Is it possible to get clearer explanations of which files need to be replaced and with what? I use Windows

I also have version 5.8.0. I wanted to stay on 5.3.0 to make it easier to find a patch, but the program automatically updated itself to the latest version

**Comment by msojocs** [comment]
In v5.8.1

1. replace Fiddler.WebUi.dll with https://github.com/msojocs/fiddler-everywhere-enhance/blob/master/v5.8.1/Fiddler.WebUi.dll
2. copy folder `server/file` to the root path of fiddler
3. copy the code of server/index.js, and paste it to the start of main.js

**Comment by AliAliaksandr** [comment]
I did all that, it's not working.

**Comment by 3Artem3** [comment]
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/51854300/c1f67ffd-96e3-4432-b17e-0acc66ba46db)

The integrity check passes and the application starts. However, there is a problem with the ports

**Comment by 3Artem3** [comment]
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/51854300/0e01fdbf-a9a0-4bd4-bc22-d91ae8caf54d)
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/51854300/7c875785-1d8f-4f22-b332-704bdc0efa86)

**Comment by msojocs** [comment]
Firstly, You should copy `server/file` instead of `server`.

Second, the error message is not 'correct', it  means file verificatin was not successful. Because the file `webui.dll` not replaced correctly.

**Comment by AliAliaksandr** [comment]
Can someone post (already ready fully patched + all needed files) version? Archive, which unpacked and runs and works. For Windows.

**Comment by 3Artem3** [comment]
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/51854300/b16c8540-9710-4e73-94e2-ad6d56818d50)

https://github.com/msojocs/fiddler-everywhere-enhance/assets/51854300/a6a5d9ed-e8d5-4e12-8161-b6851cd783f6

**Comment by 3Artem3** [comment]
https://github.com/msojocs/fiddler-everywhere-enhance/assets/51854300/81a27bb3-a48a-40ef-bc4d-5ed2060cfe75

**Comment by 3Artem3** [comment]
When replacing Fiddler.WebUi.dll, the check still stops execution

**Comment by 3Artem3** [comment]
> Can someone post (already ready fully patched + all needed files) version? Archive, which unpacked and runs and works. For Windows.


if I understand how to apply the patch. I'll make an archive like this

**Comment by msojocs** [comment]
try "./electron.exe" instead of "./electron.exe main.js"

**Comment by 3Artem3** [comment]
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/51854300/4116a26d-8b9b-4e07-b168-91d1ee96e44b)
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/51854300/fed673ca-3f22-46b1-a686-75dfaa0ad783)

**Comment by 3Artem3** [comment]
Likewise, `webui.dll` fails verification
