### ISSUE TITLE
尝试5.8.1版本，无法启动fiddler，麻烦看一下步骤是否有误

### ISSUE THREAD

**Issue by taoqjh** [msojocs/fiddler-everywhere-enhance#49]
1、https://github.com/msojocs/fiddler-everywhere-enhance/blob/master/v5.8.1/Fiddler.WebUi.dll
文件覆盖Fiddler Everywhere\resources\app\out\WebServer\Fiddler.WebUi.dll
2、server/file文件夹复制到xxxx\resources\app\out目录内
3、编辑xxx\resources\app\out\WebServer\ClientApp\dist\main.xxxxxxx.js，全部搜索https://api.getfiddler.com，
替换成http://127.0.0.1:5678/api.getfiddler.com
4、编辑xxxx\resources\app\out\main.js，在文件首行添加server/index.js内全部内容
5、重启fiddler everywhere后无反应，软件无法启动
请大佬看一下操作步骤是否有误

**Comment by msojocs** [comment]
搜索 `https://identify.getfiddler.com` 替换成 `http://127.0.0.1:5678/identify.getfiddler.com`

**Comment by taoqjh** [comment]
> 搜索 `https://identify.getfiddler.com` 替换成 `http://127.0.0.1:5678/identify.getfiddler.com`

identity.getfiddler.com已替换，软件依旧无法启动

**Comment by msojocs** [comment]
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/20937135/019be49b-0984-4b96-8de5-981027dc4cae)

**Comment by taoqjh** [comment]
感谢大佬，成功启动。膜拜~~~

**Comment by ITManCHINA** [comment]
如图所示，我这边的main.xxx.js怎么只有`identity`的链接而不是`identify`啊，这个有影响吗（都是`5.8.1`的版本）

![1716192425403](https://github.com/msojocs/fiddler-everywhere-enhance/assets/50987405/7a69ce82-0036-4031-aa2b-f392c94d321c)
