### ISSUE TITLE
开启程序窗口后显示空白

### ISSUE THREAD

**Issue by yanbchr** [msojocs/fiddler-everywhere-enhance#50]
您好，按照步骤可以打开程序，但是打开后的窗口显示内容为空是怎么回事呢？
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/50471863/6d9b0f8f-84ec-45ec-9a66-78835dbe90be)

**Comment by msojocs** [comment]
这个不清楚什么情况。

**Comment by yanbchr** [comment]
好的。谢谢

> 这个不清楚什么情况。

**Comment by msojocs** [comment]
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/20937135/a464c1b9-36ae-4d5a-847b-cd50cea88838)

你的界面跟我这边有不少不一样的。

**Comment by msojocs** [comment]
你按一下Ctrl+Shift+I看能不能调出控制台，看看有没有报错。
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/20937135/9f0df22a-58a2-4adc-ad9e-27fbedf2537a)

**Comment by nutterthanos** [comment]
i just get this
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/50470661/28a39075-8657-442b-8fdf-7770130834c7)

**Comment by nutterthanos** [comment]
electron 24.3.0
