### ISSUE TITLE
我應該下載哪一個？

### ISSUE THREAD

**Issue by dumbled00r** [msojocs/fiddler-everywhere-enhance#51]
我應該下載哪一個？
我使用Windows 64位，但這裡有很多不同的文件
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/82684246/da934307-4889-401b-93c9-9d7d3175adc1)

**Comment by msojocs** [comment]
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/20937135/5c1c92f3-fd39-436f-9182-12132bb86e61)
