### ISSUE TITLE
http://127.0.0.1:5678/identify.getfiddler.com/oauth/authorize request

### ISSUE THREAD

**Issue by nutterthanos** [msojocs/fiddler-everywhere-enhance#54]
im getting this after clicking the sign in/create account button in Fiddler Everywhere V5.8.1
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/50470661/b07bd682-8a1a-48d1-aa5d-9a7e30403d01)
![image](https://github.com/msojocs/fiddler-everywhere-enhance/assets/50470661/9e48f3cd-1052-49aa-9000-cc3b18084142)
[2024-05-23 20:22:37:302] [Error] [Angular] Error occurred during connectivity check: Unexpected token 'o', "not implement" is not valid JSON

**Comment by msojocs** [comment]
sorry please use `identity`

**Comment by nutterthanos** [comment]
all good typos happen :)
