### ISSUE TITLE
Where is Fiddler.WebUI.dll for 5.10.0?

### ISSUE THREAD

**Issue by nutterthanos** [msojocs/fiddler-everywhere-enhance#55]

**Comment by msojocs** [comment]
it is no longer needed.

**Comment by nutterthanos** [comment]
22:45:23.531 > [Product information] Fiddler Everywhere 5.10.0
22:45:23.541 > [System information] win32 (Windows_NT/x64) - version 10.0.22631
22:45:23.657 > Initializing splash screen.
22:45:23.845 > Ensure no running cleanup nodejs and cleanup .net processes.
22:45:24.425 > Displaying splash screen.
22:45:24.959 > No matching processes to clean.
22:45:25.094 > Attempting to run server - 4 attempts left.
22:45:25.096 > Trying to start server at port [28897].
22:45:25.144 > Unable to start server process, closed with code: 4294967295
22:45:25.145 > Attempt failed with undefined.
22:45:25.146 > Attempting to run server - 3 attempts left.
22:45:25.147 > Trying to start server at port [37422].
22:45:25.176 > Unable to start server process, closed with code: 4294967295
22:45:25.177 > Attempt failed with undefined.
22:45:25.177 > Attempting to run server - 2 attempts left.
22:45:25.178 > Trying to start server at port [50271].
22:45:25.204 > Unable to start server process, closed with code: 4294967295
22:45:25.204 > Attempt failed with undefined.
22:45:25.205 > Attempting to run server - 1 attempts left.
22:45:25.205 > Trying to start server at port [39896].
22:45:25.231 > Unable to start server process, closed with code: 4294967295
22:45:25.232 > Attempt failed with undefined.
22:45:25.233 > Maximum number of attempts reached - quitting application.
22:45:25.233 > Unable to start the server, error is Maximum number of attempts reached - quitting application.
22:45:25.238 > [CPU information] The processor model is: 12th Gen Intel(R) Core(TM) i7-12700H with number of cores: 20 and working at 2.688 GHz frequency
22:45:25.238 > [Memory information] The total amount of memory is 16068.73828125 MBs.

**Comment by msojocs** [comment]
`main.xxxx.js` is modified.
`main.xxxx.original.js` is not modified.

**Comment by msojocs** [comment]
#56

**Comment by nutterthanos** [comment]
> `main.xxxx.js` is modified. `main.xxxx.original.js` is not modified.

hats exactly what i did
