### ISSUE TITLE
After I followed the correct procedure, I could not start properly (v5.10)

### ISSUE THREAD

**Issue by zhaisy** [msojocs/fiddler-everywhere-enhance#59]
<img width="1183" alt="fff" src="https://github.com/msojocs/fiddler-everywhere-enhance/assets/68274312/31e6b5d9-e935-4354-ba1b-5a34d37cc1a7">

**Comment by NBNGaming** [comment]
Most likely, you made a mistake somewhere. Everything works for me. Try again, you need to follow the [instruction](https://github.com/msojocs/fiddler-everywhere-enhance#for-v590-v5100). In step 9, you need to complete the sections [修改 main.js](https://github.com/msojocs/fiddler-everywhere-enhance#%E4%BF%AE%E6%94%B9-mainjs) and [修改 main.xxx.js](https://github.com/msojocs/fiddler-everywhere-enhance#%E4%BF%AE%E6%94%B9-mainxxxjs). Keep in mind that the Electron from the `Patch` section is no longer needed.

**Comment by zhaisy** [comment]
@NBNGaming No，I can't succeed and I can't stand it

**Comment by zhaisy** [comment]
<img width="1266" alt="un" src="https://github.com/user-attachments/assets/c0c0eb41-231d-4711-a204-91dfcbf13408">
I tried it three more times, again, I'm not sure it's the version

**Comment by zhaisy** [comment]
@msojocs I tried version 5.8.1, but the same error still occurs. I need your help
<img width="1232" alt="f" src="https://github.com/user-attachments/assets/991f5aee-c72b-41e0-b19b-74075f273a6c">

**Comment by msojocs** [comment]
1. go to `Resources/app/out/WebServer` 
2. open terminal
3. execute ` .\Fiddler.WebUi.exe --port=15150`
