### ISSUE TITLE
请问一下Mac intel芯片用哪个可行？（v X.X.X-mac 是通用的吗？）

### ISSUE THREAD

**Issue by muziyuqi** [msojocs/fiddler-everywhere-enhance#61]

**Comment by msojocs** [comment]
那是网友提交的，我不确定。

**Comment by muziyuqi** [comment]
所以现在还有Mac能用的吗😂 刚才试了[v4.0.1-mac]，闪退😂

**Comment by muziyuqi** [comment]
> 所以现在还有Mac能用的吗😂 刚才试了[v4.0.1-mac]，闪退😂
intel版本的macos

**Comment by muziyuqi** [comment]
> 所以现在还有Mac能用的吗😂 刚才试了[v4.0.1-mac]，闪退😂

intel版本的macos

**Comment by msojocs** [comment]
看样子，你得自己动手

**Comment by richard1230** [comment]
> > 所以现在还有Mac能用的吗😂 刚才试了[v4.0.1-mac]，闪退😂
> 
> intel版本的macos↳

兄弟，搞好了没，搞好了也造福一下兄弟们啊

**Comment by wwh1004** [comment]
可以的话帮我测试下MacOS的补丁，我做了个离线激活的。https://github.com/msojocs/fiddler-everywhere-enhance/issues/63
之前看到有反馈说MacOS用完会显示损坏的App，先确保启动一次Fiddler Everywhere再运行补丁。昨天拿github的ci编译出的macos的可执行文件，我本地不好测试这个。

**Comment by msojocs** [comment]
mac已支持。
