### ISSUE TITLE
你好，我根据文档进行如下操作后，遇到了问题，请您看下

### ISSUE THREAD

**Issue by GodZhai** [msojocs/fiddler-everywhere-enhance#62]
1.删除libfiddler.dll, 重命名hostpolicy.dll为hostpolicy.original.dll
2.下载https://github.com/project-yukihana/Yukihana-patch/releases的libfiddler和hostpolicy.dll，下载的为yukihana-hostpolicy-win32-x86_64-v1.0.4.dll和yukihana-libfiddler-win32-x86_64-v1.0.4.dll
3.把下载的改名为libfiddler.dll放到根目录
4.把下载的改名为hostpolicy.dll放到resources\app\out\WebServer下
5.创建resources\app\out\WebServer\patch.json文件，并写入如图内容
![1](https://github.com/user-attachments/assets/ceb1b93d-0f52-45e9-86cd-9366a3ff7567)
6.拷贝ClientApp\\dist\\main.5f4387a481528ff0.js为ClientApp\\dist\\main.5f4387a481528ff0.original.js
7.拷贝resources\app\out\main.js为resources\app\out\main.original.js
8.修改这两个main文件，
修改 main.js
打开 resources/app/out/main.js
server/index.js 的内容添加到 resources/app/out/main.js 开头
修改 main.xxx.js
打开 resources/app/out/WebServer/ClientApp/dist/main.xxx.js
替换所有 https://api.getfiddler.com 为 http://127.0.0.1:5678/api.getfiddler.com
替换所有 https://identity.getfiddler.com 为 http://127.0.0.1:5678/identity.getfiddler.com
9.下载Electron https://github.com/electron/electron/releases , 下载的为v29.4.4，解压到Electron文件夹，Electron和Fiddle EveryWhere在同级目录如图
![2](https://github.com/user-attachments/assets/c57c50d9-750e-49a3-aea1-6ed01dd70e62)
10.复制 server/file -> Electron/resources/app/out/file，然后运行，出现如下问题
![3](https://github.com/user-attachments/assets/e297d88e-ef3b-41b7-9082-eb62b30b6d1d)
![4](https://github.com/user-attachments/assets/023e44ca-de93-4b49-ae26-646b740c2b22)

**Comment by GodZhai** [comment]
@msojocs 在吗大佬？

**Comment by msojocs** [comment]
file文件夹复制不正确
