### ISSUE TITLE
离线授权补丁（Windows/Linux/MacOS）

### ISSUE THREAD

**Issue by wwh1004** [msojocs/fiddler-everywhere-enhance#63]
做了个离线授权的补丁，考虑合并进去么？
Windows：
直接运行，输入安装路径（留空自动查找默认的）。
<img width="735" alt="Snipaste_2024-07-29_23-05-06" src="https://github.com/user-attachments/assets/79e7e071-6983-4eb7-bfe5-633b757ca79a">
<img width="1095" alt="Snipaste_2024-07-29_23-05-15" src="https://github.com/user-attachments/assets/0cbd60f8-42f0-43af-9c8c-07a4c78a8731">
Linux：
直接运行，输入Fiddler Everywhere路径（AppImage释放后的squashfs-root）。
<img width="973" alt="Snipaste_2024-07-29_22-24-54" src="https://github.com/user-attachments/assets/e06b7d78-d48e-46f7-a0c6-dbce0bc986ad">
<img width="957" alt="Snipaste_2024-07-29_22-26-04" src="https://github.com/user-attachments/assets/a7321e38-31bf-4a8e-a5f2-072cb1e8ad7a">
MacOS：
直接运行，输入安装路径（留空自动查找默认的）。
<img width="513" alt="Snipaste_2024-07-29_22-31-01" src="https://github.com/user-attachments/assets/64a8d553-8ebb-4982-9f95-65d5d1cdaa90">
<img width="519" alt="Snipaste_2024-07-29_22-31-11" src="https://github.com/user-attachments/assets/5085a272-8082-4558-b868-0d2e8421f68b">

补丁：
[FiddlerEverywherePatcher-win-x64.zip](https://github.com/user-attachments/files/16415317/FiddlerEverywherePatcher-win-x64.zip)
[FiddlerEverywherePatcher-linux-x64.zip](https://github.com/user-attachments/files/16415314/FiddlerEverywherePatcher-linux-x64.zip)
[FiddlerEverywherePatcher-osx-x64.zip](https://github.com/user-attachments/files/16415312/FiddlerEverywherePatcher-osx-x64.zip)
[FiddlerEverywherePatcher-osx-arm64.zip](https://github.com/user-attachments/files/16415316/FiddlerEverywherePatcher-osx-arm64.zip)

**Comment by wwh1004** [comment]
这样呢，我已经编译了全平台的。不需要虚拟机，直接运行就可以了，完全自动化的，不麻烦了。补丁完不需要登录了，也不会显示试用标志。

**Comment by msojocs** [comment]
也不合并，你可以提交一个pr，然后我在readme指向这个pr。

**Comment by 1011382654** [comment]
太好用了 谢谢大佬

**Comment by isPony** [comment]
[FiddlerEverywherePatcher-osx-x64.zip](https://github.com/user-attachments/files/16415312/FiddlerEverywherePatcher-osx-x64.zip)
@wwh1004  请问这个适用于什么版本？我尝试了5.15.1/5.10.0/5.9.0都不行
- 安装好Fiddle，未打开Fiddle，安装补丁能成功，但是打开Fiddle，提示“Fiddler Everywhere” is damaged and can’t be opened. You should move it to the Trash.”
- 安装好Fiddle，打开Fiddle，安装补丁未能成功，提示“Unhandled Exception: System.UnauthorizedAccessException: Access to the path '/Applications/Fiddler Everywhere.app/Contents/Frameworks/libfiddler.dylib.00000000.bak' is denied.
 ---> System.IO.IOException: Operation not permitted”，sudo 执行输入完密码就卡主
- 安装好Fiddle，打开Fiddle，手工替换“libfiddler.dylib、Fiddler.WebUi.dll”，打开就闪退

**Comment by wwh1004** [comment]
安装完fiddler everywhere先启动一次。然后关掉fiddler everywhere。最后运行补丁。如果出现文件占用就重启电脑，肯定是你没退干净fiddler，我碰到好多次这种反馈了。

**Comment by isPony** [comment]
> 安装完fiddler everywhere先启动一次。然后关掉fiddler everywhere。最后运行补丁。如果出现文件占用就重启电脑，肯定是你没退干净fiddler，我碰到好多次这种反馈了。

5.15.1/5.10.0/5.9.0 这几个版本都支持吗？ 我也试过重启，我再试试。tks

**Comment by isPony** [comment]
@wwh1004 
系统是14.4.1 (23E224)，安装5.15.1，重启还是不行，也确定已经退出了Fiddle
![2024-08-22_17-10-52](https://github.com/user-attachments/assets/3c98d5f4-93fb-4253-ad5f-43efdb444082)
![2024-08-22_17-12-54](https://github.com/user-attachments/assets/e2d56964-8944-4f05-8133-6c770de75461)

我提取了你补丁中的“libfiddler.dylib、Fiddler.WebUi.dll”这两个文件，手工替换包里的文件，替换后运行Fiddle就闪退

**Comment by wwh1004** [comment]
那我就不知道了，读写文件没权限这个大概率和补丁没什么关系，文件被占用，或者补丁进场没权限都有可能。其他人那边还有我自己没遇到过你这种重启了还提示没权限的

**Comment by sipsuru** [comment]
Well, this doesn't work for FE 5.17.0 + due to renaming of "libfiddler.dll" but works for 5.9.0 - 5.16.0.

Can you consider making the source avaiable?  

---

> [!NOTE]
> 使用AI翻译

嗯，这在FE 5.17.0及以上版本中不起作用，因为“libfiddler.dll”被重命名了，但在5.9.0到5.16.0版本中有效。

你能考虑公开源代码吗？

**Comment by wwh1004** [comment]
@sipsuru I am worried that open source could lead to an uncontrollable situation.

If you want to know what has been patched, you can use dnSpy to decompile and compare ReadOfflineLicenseFile/GetOfflineLicense/GetCurrentUserADEmail/GetCurrentUserADPrincipalName/get_IsPlatformSupported.

I don't know the security  mechanism about MacOS so I can't patch the dylib binary. Here are the updates for 5.17.0+ excluding MacOS:
[FiddlerEverywherePatcher-win-x64_2024-09-24.zip](https://github.com/user-attachments/files/17173896/FiddlerEverywherePatcher-win-x64_2024-09-24.zip)
[FiddlerEverywherePatcher-linux-x64_2024-09-24.zip](https://github.com/user-attachments/files/17173895/FiddlerEverywherePatcher-linux-x64_2024-09-24.zip)

**Comment by lovezm** [comment]
<img width="281" alt="image" src="https://github.com/user-attachments/assets/264d4cc1-7bec-49e9-adc1-8255717aa05b" />
我试了这两个版本的，打开就自动更新 改 main 禁用更新就 损坏了 大佬

**Comment by iamumairayub** [comment]
@wwh1004 

I did install version 5.10.0 on my Windows 10

Installed your patch, it went good

But when I launched Fiddler app, it immediately started to upgrade to newest version
no way to stop that update

After update, It then shows that your trial has expired

**Comment by iamumairayub** [comment]
@wwh1004 https://github.com/auto-yui-patch/fiddler-everywhere-patch-automated this worked perfectly for me

So easy to use

<img width="415" height="318" alt="Image" src="https://github.com/user-attachments/assets/9d5edae1-bef2-43aa-b466-6176ea75586d" />

my trial expires in 999 days ... LOL
