### ISSUE TITLE
mac 无修改实现

### ISSUE THREAD

**Issue by msojocs** [msojocs/fiddler-everywhere-enhance#64]
遇到一点小问题：

![image](https://github.com/user-attachments/assets/fd67a53a-40a0-4c33-9fc8-8d83fea473d6)

**Comment by liubin595338764** [comment]
@msojocs 你是如何实现的，可以帮助我破解吗，我已经尝试好多次都无法实现破解

**Comment by msojocs** [comment]
> @msojocs 你是如何实现的，可以帮助我破解吗，我已经尝试好多次都无法实现破解

我在 Intel CPU 的虚拟机里跑的，M1只是编译了一下。

https://github.com/msojocs/fiddler-everywhere-enhance/issues/65 这里是M1可以开启，但是不能抓包。
