### ISSUE TITLE
Mac m1 破解后无法打开程序

### ISSUE THREAD

**Issue by longyi-xw** [msojocs/fiddler-everywhere-enhance#65]
![CleanShot 2024-08-03 at 21 25 13@2x](https://github.com/user-attachments/assets/8d3e33ac-6db5-4698-a867-6bd4119f0d3b)
macos 14.5 (23F79)

我尝试自己编译 libfiddler.dylib 
<img width="1048" alt="image" src="https://github.com/user-attachments/assets/4b8f093f-aebf-4169-8672-068a5b28d2f6">
没有 /scripts/buildsystems/vcpkg.cmake 文件，我并不熟悉c++，请问这种情况有什么方案吗？

**Comment by longyi-xw** [comment]
@msojocs 刚才输m结果github不小心提交了

**Comment by msojocs** [comment]
你确定下载的是arm64版本？

**Comment by msojocs** [comment]
自行编译要：
1. 安装vcpkg https://github.com/microsoft/vcpkg
2. 设定VCPKG_ROOT环境变量

**Comment by msojocs** [comment]
![image](https://github.com/user-attachments/assets/338b647d-5860-47d5-9a38-1848450eb7e2)

![image](https://github.com/user-attachments/assets/6f6d3c4a-85bd-493e-a587-7958752b7360)

疑似Action的环境有问题

**Comment by msojocs** [comment]
![image](https://github.com/user-attachments/assets/17c47218-3cf4-425f-a8d0-ca54cd212f14)

应该是这个问题，我之后改一下。

**Comment by msojocs** [comment]
试一下最新的

**Comment by longyi-xw** [comment]
> 试一下最新的

最新的可以了，感谢！
但是有个新的问题，进入软件后无法开启HTTPS抓包，但我不确定是不是我电脑的问题，因为登录和系统中分别添加了fiddler的证书信任
<img width="1214" alt="image" src="https://github.com/user-attachments/assets/c2eb48dc-ee1a-462d-be5d-9ff862acf085">
<img width="995" alt="image" src="https://github.com/user-attachments/assets/71b70fff-e5b3-42fa-9e8e-1965a9b61f5e">

**Comment by msojocs** [comment]
![image](https://github.com/user-attachments/assets/44b0b082-c6a9-4b97-abba-a7a0fec1e366)

不清楚什么情况

**Comment by msojocs** [comment]
![image](https://github.com/user-attachments/assets/4d08b26c-6e82-4250-8405-c839539c6905)

**Comment by longyi-xw** [comment]
好的，谢谢，我排查一下我这边的原因
