### ISSUE TITLE
MAC M1 arm 5.3.0 替换文件后打开闪退有装过这个版本的没里边就一个文件

### ISSUE THREAD

**Issue by fengxuezhan** [msojocs/fiddler-everywhere-enhance#66]

**Comment by longyi-xw** [comment]
用最新方法，5.14版本没问题，但是我的有证书问题导致开启不了https，你可以试一下你的

**Comment by fengxuezhan** [comment]
> 用最新方法，5.14版本没问题，但是我的有证书问题导致开启不了https，你可以试一下你的

最新方法?,不是4.0版本的方法么

**Comment by fengxuezhan** [comment]
@longyi-xw 你用的哪个文件替换的,我看他最新的破解文件礼里边只有一个文件

**Comment by longyi-xw** [comment]
> @longyi-xw 你用的哪个文件替换的,我看他最新的破解文件礼里边只有一个文件

作者前几天更新这个
![image](https://github.com/user-attachments/assets/7bef91d2-5b33-4946-9b19-4f4a2881cae3)

**Comment by fengxuezhan** [comment]
@longyi-xw 好的感谢, 我之前替换的他文件夹: [v5.3.0/macOS/apple] 这个文件搞了好一会都是闪退

**Comment by longyi-xw** [comment]
> @longyi-xw 好的感谢, 我之前替换的他文件夹: [v5.3.0/macOS/apple] 这个文件搞了好一会都是闪退

5.3好像是其他人提交的，我之前修改成功了也抓不到https我怀疑是我电脑有问题，但是旧方法没有了，所以你替换了肯定成功不了，要用electron换个壳，然后修改main.xxx 和 main.js 还要把server文件夹的内容拷进去

**Comment by fengxuezhan** [comment]
@longyi-xw 你清下证书信息这玩意你不手动删搞不干净,历史的清干净,刷新下缓存配置

**Comment by longyi-xw** [comment]
> @longyi-xw 你清下证书信息这玩意你不手动删搞不干净,历史的清干净,刷新下缓存配置

试过也不行，不知道为什么就是检测不到证书，公司的windows修改过很多次都没有这种问题，所以看看你的有这种问题不

**Comment by fengxuezhan** [comment]
@longyi-xw 
<img width="814" alt="image" src="https://github.com/user-attachments/assets/48b7515a-c333-4d43-81f6-0906d5165000">
这个文件那里找到

**Comment by fengxuezhan** [comment]
@longyi-xw 最后的copy文件是在哪里下载知道么copy ClientApp/dist/main-XSH4ELY7.js to ClientApp/dist/main-XSH4ELY7.original.js

copy Resources/app/out/main.js to Resources/app/out/main.original.js

modify file main-XSH4ELY7.js and file main.js as usual.

copy server/file -> Contents/Resources/app/out/file

You may need to recompile libfiddler and libopen by yourself.

**Comment by longyi-xw** [comment]
> @longyi-xw 最后的copy文件是在哪里下载知道么copy ClientApp/dist/main-XSH4ELY7.js to ClientApp/dist/main-XSH4ELY7.original.js
> 
> copy Resources/app/out/main.js to Resources/app/out/main.original.js
> 
> modify file main-XSH4ELY7.js and file main.js as usual.
> 
> copy server/file -> Contents/Resources/app/out/file
> 
> You may need to recompile libfiddler and libopen by yourself.

就是ClientApp/dist/main-xxx.js 和 Resources/app/out/main.js 下面的文件 右键应用包内容里面

**Comment by fengxuezhan** [comment]
@longyi-xw 我知道这个文件下,但是他不是写copy 两个文件都在一个目录下

**Comment by fengxuezhan** [comment]
@longyi-xw  copy ClientApp/dist/main-XSH4ELY7.js to ClientApp/dist/main-XSH4ELY7.original.js  这文件

**Comment by longyi-xw** [comment]
> @longyi-xw copy ClientApp/dist/main-XSH4ELY7.js to ClientApp/dist/main-XSH4ELY7.original.js 这文件

就是复制一哈改个名字

**Comment by fengxuezhan** [comment]
> > @longyi-xw copy ClientApp/dist/main-XSH4ELY7.js to ClientApp/dist/main-XSH4ELY7.original.js 这文件
> 
> 就是复制一哈改个名字

哦哦, 我以为还有其他文件

**Comment by fengxuezhan** [comment]
@longyi-xw 
<img width="700" alt="image" src="https://github.com/user-attachments/assets/a41974ec-8b9e-488f-b3b2-00324d1055e5">
zh这个文件需要重新编译么

**Comment by longyi-xw** [comment]
不用

**Comment by fengxuezhan** [comment]
> 不用

这个文件我怎没找到 server/index.js 的内容添加到 resources/app/out/main.js 开头

**Comment by longyi-xw** [comment]
> > 不用
> 
> 这个文件我怎没找到 server/index.js 的内容添加到 resources/app/out/main.js 开头

在server下面
![image](https://github.com/user-attachments/assets/2a7fe082-5b34-4fe7-a436-7802ca09c83c)

**Comment by fengxuezhan** [comment]
@longyi-xw 用的5.15版本还是闪退

**Comment by longyi-xw** [comment]
> @longyi-xw 用的5.15版本还是闪退

sudo xattr -r -d com.apple.quarantine 把软件拖到这

**Comment by fengxuezhan** [comment]
> > @longyi-xw 用的5.15版本还是闪退
> 
> sudo xattr -r -d com.apple.quarantine 把软件拖到这

跳过这个认证还是不行, 直接就报错日志弹出来, 人都麻了

**Comment by longyi-xw** [comment]
日志截个图

**Comment by fengxuezhan** [comment]
> 日志截个图

你能把你的5.14版本导出来我下不

**Comment by longyi-xw** [comment]
> > 日志截个图
> 
> 你能把你的5.14版本导出来我下不

应该不是版本问题，因为我15也成功过，你仔细看下日志报错提示的什么

**Comment by fengxuezhan** [comment]
<img width="858" alt="image" src="https://github.com/user-attachments/assets/c3f1d5c7-32c5-4e1d-a2c4-2486b6d3594a">
你是按照他这个文件名还是替换自己的,我看自己目录的原文件名字跟这个有区别我替换掉了

**Comment by fengxuezhan** [comment]
@longyi-xw

**Comment by longyi-xw** [comment]
@fengxuezhan 

没遇到过，你可以针对这个问题重新发一个issue，然后你下载14版本试一下吧，14也还不行那可能就只有作者什么时候有时间看一下了
https://downloads.getfiddler.com/mac-arm64/Fiddler Everywhere 5.14.dmg
我看最新版本已经是 5.15.1 了可能官方已经做了防御

**Comment by longyi-xw** [comment]
> <img alt="image" width="858" src="https://private-user-images.githubusercontent.com/71437042/355742122-c3f1d5c7-32c5-4e1d-a2c4-2486b6d3594a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjA1MjAsIm5iZiI6MTcyMzAyMDIyMCwicGF0aCI6Ii83MTQzNzA0Mi8zNTU3NDIxMjItYzNmMWQ1YzctMzJjNS00ZTFkLWEyYzQtMjQ4NmI2ZDM1OTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA4NDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ZTNhZjlmZWUyNTBmYjg3N2FhMGMzZWYzYjYzNTAyY2RhYzUzMGYxY2JjZGE1MjE2ZTIxNTg5MmVjOWY1M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vjv6PBZPBDhQ4TTLt6LmO3xAOAT4pzyrNdqVU6n738E"> 你是按照他这个文件名还是替换自己的,我看自己目录的原文件名字跟这个有区别我替换掉了

替换是对的

**Comment by fengxuezhan** [comment]
> > <img alt="image" width="858" src="https://private-user-images.githubusercontent.com/71437042/355742122-c3f1d5c7-32c5-4e1d-a2c4-2486b6d3594a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjA1MjAsIm5iZiI6MTcyMzAyMDIyMCwicGF0aCI6Ii83MTQzNzA0Mi8zNTU3NDIxMjItYzNmMWQ1YzctMzJjNS00ZTFkLWEyYzQtMjQ4NmI2ZDM1OTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA4NDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ZTNhZjlmZWUyNTBmYjg3N2FhMGMzZWYzYjYzNTAyY2RhYzUzMGYxY2JjZGE1MjE2ZTIxNTg5MmVjOWY1M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vjv6PBZPBDhQ4TTLt6LmO3xAOAT4pzyrNdqVU6n738E"> 你是按照他这个文件名还是替换自己的,我看自己目录的原文件名字跟这个有区别我替换掉了
> 
> 替换是对的

低版本包没法下载了吧你有么

**Comment by longyi-xw** [comment]
上面发了链接

**Comment by fengxuezhan** [comment]
> https://downloads.getfiddler.com/mac-arm64/Fiddler

链接地址打不开

**Comment by longyi-xw** [comment]
> > https://downloads.getfiddler.com/mac-arm64/Fiddler
> 
> 链接地址打不开

[https://downloads.getfiddler.com/mac-arm64/Fiddler Everywhere 5.14.0.dmg](url)

**Comment by fengxuezhan** [comment]
> > > https://downloads.getfiddler.com/mac-arm64/Fiddler
> > 
> > 
> > 链接地址打不开
> 
> [https://downloads.getfiddler.com/mac-arm64/Fiddler Everywhere 5.14.0.dmg](url)

好的,我再试试吧 感谢

**Comment by msojocs** [comment]
> @longyi-xw <img alt="image" width="894" src="https://private-user-images.githubusercontent.com/71437042/355739286-1402582f-88a6-4160-82ce-c7992c313e38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjU3MTEsIm5iZiI6MTcyMzAyNTQxMSwicGF0aCI6Ii83MTQzNzA0Mi8zNTU3MzkyODYtMTQwMjU4MmYtODhhNi00MTYwLTgyY2UtYzc5OTJjMzEzZTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDEwMTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YmIwOWRmOGQ5YjllOGQzNTdiMDJiODA2YWVmZDBiYmE3OTI3YWRiMzQwZjAxNTMyZjQ1YmM0ZTg2YjY1NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OTuL5a-jKM_3V1yBNPu4XO3wO34Kd6lDMTplfGq4J-g"> 你看下遇到过没

签名问题处理：
1. 重新安装
2. 启动，过校验
3. 关闭软件
4. 修改
5. 启动

**Comment by fengxuezhan** [comment]
> > @longyi-xw <img alt="image" width="894" src="https://private-user-images.githubusercontent.com/71437042/355739286-1402582f-88a6-4160-82ce-c7992c313e38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjU3MTEsIm5iZiI6MTcyMzAyNTQxMSwicGF0aCI6Ii83MTQzNzA0Mi8zNTU3MzkyODYtMTQwMjU4MmYtODhhNi00MTYwLTgyY2UtYzc5OTJjMzEzZTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDEwMTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YmIwOWRmOGQ5YjllOGQzNTdiMDJiODA2YWVmZDBiYmE3OTI3YWRiMzQwZjAxNTMyZjQ1YmM0ZTg2YjY1NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OTuL5a-jKM_3V1yBNPu4XO3wO34Kd6lDMTplfGq4J-g"> 你看下遇到过没
> 
> 签名问题处理：
> 
> 1. 重新安装
> 2. 启动，过校验
> 3. 关闭软件
> 4. 修改
> 5. 启动

要先启动再去修改么,我倒是下载了直接改没启动

**Comment by fengxuezhan** [comment]
@msojocs 下载启动之后需要注册登录不, 还是只是到登录页面就可关闭修改

**Comment by msojocs** [comment]
> @msojocs 下载启动之后需要注册登录不, 还是只是到登录页面就可关闭修改

登录页面看见就行
