### ISSUE TITLE
windows10专业版22H2按照指定操作后无法打开fiddler

### ISSUE THREAD

**Issue by xichangyue** [msojocs/fiddler-everywhere-enhance#69]
我按照此项目的github主页指引进行操作，完成后打开fiddler提示以下错误：
![image](https://github.com/user-attachments/assets/6e26a2bc-f277-4abf-9ce6-91ae6b1ed9d0)
我安装的fiddler版本为：Fiddler Everywhere 5.15.1
我使用的libfiddler.dll和hostpolicy.dll版本为1.0.9
可以帮我看看是什么问题吗，感谢🙏。

**Comment by msojocs** [comment]
我5.16.0都可以，你的操作不对。
