### ISSUE TITLE
Infinite loading on windows for v3.3 

### ISSUE THREAD

**Issue by RootEncrypter** [msojocs/fiddler-everywhere-enhance#7]
Built the webui and backendsdk for windows. Also made changes to the mainxxx.js file. But after cracking it just keeps  loading. Please help

**Comment by RootEncrypter** [comment]
@msojocs

**Comment by msojocs** [comment]
It is working for me.
You may do something not in a right way.

**Comment by RootEncrypter** [comment]
I converted the dlls to il and edited using notepad++ then changed back to dll. I rebuilt them for windows. Do you think I should change something?

**Comment by RootEncrypter** [comment]
Could you tell the iL like numbers to delete for TryOpenClientMainScript and TryOpenElectronMainScript

**Comment by msojocs** [comment]
this two functions in `Fiddler.WebUi` are easy to modify.
the important file is `FiddlerBackendSDK.dll`, you should make the function named `FiddlerBackendSDK.User.UserClient::GetBestAccount` return the first element directly.

**Comment by RootEncrypter** [comment]
@msojocs what are the line numbers to delete in Fiddler.WebUi?

**Comment by msojocs** [comment]
from
```c#
public AccountDTO GetBestAccount(UserWithBestAccountDTO user)
{
	if (user.BestEverywhereAccountId != null)
	{
		return user.Accounts.FirstOrDefault((UserAccountDTO x) => x.Id == user.BestEverywhereAccountId.Value);
	}
	return null;
}
```
to
```c#
public AccountDTO GetBestAccount(UserWithBestAccountDTO user)
{
	return user.Accounts.FirstOrDefault((UserAccountDTO x) => true);
}
```

**Comment by RootEncrypter** [comment]
@msojocs  made the changes. It looks like this now.
![image](https://user-images.githubusercontent.com/62509239/180612917-9c692644-dfe9-43f8-9715-60811b789a92.png)

Im having problems with "Fiddler.WebUi".  What lines should i edit in TryOpenClientMainScript and TryOpenElectronMainScript.
Please tell IL line numbers for TryOpenClientMainScript  and TryOpenElectronMainScript

**Comment by msojocs** [comment]
just make these functions return `true` directly.
like this:
```c#
public boolean TryXxxx (){
    // delete all
    return true;
}
```

**Comment by RootEncrypter** [comment]
lol new update now 3.3.1 @msojocs

**Comment by msojocs** [comment]
> lol new update now 3.3.1 @msojocs

yeah, the method is also working with `v3.3.1`.

**Comment by msojocs** [comment]
> lol new update now 3.3.1 @msojocs

yeah, this method also works with `v3.3.1`.

**Comment by RootEncrypter** [comment]
I updated crack for 3.3.1. Here are the screenshots
![1](https://user-images.githubusercontent.com/62509239/180639331-da1f6a75-6d85-48ae-9429-eddbe68a8016.png)
![2](https://user-images.githubusercontent.com/62509239/180639333-70903b5b-9777-4f75-88d0-cc4d891b04f0.png)
![3](https://user-images.githubusercontent.com/62509239/180639335-cd4a7196-c411-44a3-9acd-990ce0c99759.png)
![4](https://user-images.githubusercontent.com/62509239/180639339-adf55745-5c24-4ee4-886e-f636dca7c65b.png)

I have done everything correctly but its still not working for windows. Its loading infinitely in windows. @msojocs Please tell me whats wrong. ?

**Comment by msojocs** [comment]
sorry I do not know.

**Comment by cabiamdos** [comment]
yes it happens the same problem to me, infinite loading after doing all the steps right

**Comment by cabiamdos** [comment]
> I updated crack for 3.3.1. Here are the screenshots ![1](https://user-images.githubusercontent.com/62509239/180639331-da1f6a75-6d85-48ae-9429-eddbe68a8016.png) ![2](https://user-images.githubusercontent.com/62509239/180639333-70903b5b-9777-4f75-88d0-cc4d891b04f0.png) ![3](https://user-images.githubusercontent.com/62509239/180639335-cd4a7196-c411-44a3-9acd-990ce0c99759.png) ![4](https://user-images.githubusercontent.com/62509239/180639339-adf55745-5c24-4ee4-886e-f636dca7c65b.png)
> 
> I have done everything correctly but its still not working for windows. Its loading infinitely in windows. @msojocs Please tell me whats wrong. ?

what program for debugging and which OS are you using?

**Comment by cabiamdos** [comment]
![image](https://user-images.githubusercontent.com/82284393/197408033-5e298d15-72d1-4832-b689-0afa71e2eb16.png)
![image](https://user-images.githubusercontent.com/82284393/197408062
[main.zip](https://github.com/msojocs/fiddler-everywhere-crack/files/9847197/main.zip)
-d392d41b-ea50-440f-9f3a-08fff564e7af.png)

[main.9c27a5768c5c6da2.js.zip](https://github.com/msojocs/fiddler-everywhere-crack/files/9847200/main.9c27a5768c5c6da2.js.zip)


![image](https://user-images.githubusercontent.com/82284393/197407977-628a8d63-4aeb-47c6-9544-3ff0decb3e54.png)

**Comment by cabiamdos** [comment]
after testing a little bit there is a problem with the edit in the main.xxx.js because I used the original one (but the other two .dll modified and the main.js too) and it could entered in the app. Let me see if I can fix this right now, will keep you updated

**Comment by cabiamdos** [comment]
### Update, there is a problem with the license. 

After modifying the file a little bit still don't know how to fix this (I changed more lines btw) but the problem is 100% in the main.xxx.js
I thought this will fix but I will keep update. Still working

![image](https://user-images.githubusercontent.com/82284393/197410651-37a61a97-83fd-4cef-a4a6-31a3567da013.png)

**Comment by cabiamdos** [comment]
![image](https://user-images.githubusercontent.com/82284393/197411871-514c9a53-1c94-405b-920e-24f02deea510.png)

**Comment by RootEncrypter** [comment]
There is an infinite loading error even after cracking. @msojocs could you send the updated crack files for windows please?

**Comment by cabiamdos** [comment]
this should be the endpoint on the fetch function, howerver when you use this in another js file or postman it always receives 400 bad request. 
`import fetch from "node-fetch";

const k = {
  AuthFlow:"USER_PASSWORD_AUTH",ClientId:"34vrraouuamaupd21r16tsb6aq",
  AuthParameters:{
    "USERNAME":"emailATgmail.com",
    "PASSWORD":"yourPassword"
  },
  ClientMetadata:{
    migrationInvokedFromSignin:true,
    clientId:""
  }
}

fetch('https://cognito-idp.us-east-1.amazonaws.com/', 
  {
    headers: {
      "Content-Type":"application/x-amz-json-1.1",
      "X-Amz-Target":"AWSCognitoIdentityProviderService.InitiateAuth",
      "X-Amz-User-Agent":"aws-amplify/0.1.x js"
    },
    method:"POST",
    mode:"cors",
    cache:"no-cache",
    body: JSON.stringify(k)
  }
).then(res => {
  console.log('res', res);
  res.json()
})
.then(data => console.log(data))
.catch(err => console.log(err));`


But the response object should be something like this (in the res.json()):
`
// RESPONSE AUTHENTICATION TOKEN
              // at: {}, je: {"AuthenticationResult":{"AccessToken":"eyJraWQiOiIrYlducUg4bEo3TStcL2x4OTgrZllNbHdtNDFqZVYrOTFEWnZ6WFhnVHNiVT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIzZmIzODk4YS03MGY3LTRlNzYtYTU0Ni1iZjE5YzczNDI3OGIiLCJldmVudF9pZCI6Ijc2NTI2ODM0LWEyMWMtNGI5OS04NTNmLWM5MzJjNzYyMDYxNSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2NjY1Njk4MDcsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX1lwVnlNNFNvciIsImV4cCI6MTY2NjU3MzQwNywiaWF0IjoxNjY2NTY5ODA3LCJqdGkiOiI3ZTY5OTQ0Zi00NWJjLTQ5N2MtYWZlMy04MjA4YjMyYzcyNjciLCJjbGllbnRfaWQiOiIzNHZycmFvdXVhbWF1cGQyMXIxNnRzYjZhcSIsInVzZXJuYW1lIjoieXZpdW53YXR5YW5kZXguY29tIn0.N7DG2m6xVNLwCHLNsiHsf7LEP35rnxbAsf9PNJjevsf2I1IUT5yX0I4_0S7lp0m7o_XdH82FzJ4BeiPEOlo3qLF5QZtyQPbsWc1Y_x0NZB3xEX-Jh_YCgC0KGJQL8pOgRkqKPMBgYey1X6c-PkYIp9lhKs5CC96aFJakVbCCHKe0kgzqL4yo3TWWbZVTjYfxdeeCHEh3wbpzLGX3_lGi7z2lclpoGKaAzrVL6u9vYcxZyY9t8tlaQ_Ai88bocvbENmL3FmIZxUXrHcd094Qnx6B1GpvOV1OijhEgOiFqoxHqQEl4Rtg1cOA7U_rx0Gx2GIW6px6xiyaLfNBcrH5R1g","ExpiresIn":3600,"IdToken":"eyJraWQiOiJ1OHJCdTE2eDYrTUlHQkJUS2JwXC9GTmw0bW4zMkdLMUtmeU5pZGxhc3pxQT0iLCJhbGciOiJSUzI1NiJ9.eyJjdXN0b206Y291bnRyeSI6IlNwYWluIiwic3ViIjoiM2ZiMzg5OGEtNzBmNy00ZTc2LWE1NDYtYmYxOWM3MzQyNzhiIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImN1c3RvbTpldmVyeXdoZXJlX2V1bGEiOiIzLjIuMCIsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX1lwVnlNNFNvciIsImN1c3RvbTptYXJrZXRpbmdfb3B0ZWQiOiJubyIsImNvZ25pdG86dXNlcm5hbWUiOiJ5dml1bndhdHlhbmRleC5jb20iLCJjdXN0b206c3RhdGUiOiJOVUxMIiwiY3VzdG9tOmNvbXBhbnkiOiJOQU4iLCJhdWQiOiIzNHZycmFvdXVhbWF1cGQyMXIxNnRzYjZhcSIsImN1c3RvbTpsYXN0X25hbWUiOiJOb3NlIiwiZXZlbnRfaWQiOiI3NjUyNjgzNC1hMjFjLTRiOTktODUzZi1jOTMyYzc2MjA2MTUiLCJjdXN0b206Zmlyc3RfbmFtZSI6IlJvYmVydCIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNjY2NTY5ODA3LCJjdXN0b206cGhvbmVfbnVtYmVyIjoiNjY0ODI5MjAzIiwiZXhwIjoxNjY2NTczNDA3LCJjdXN0b206cm9sZSI6IlN0dWRlbnQiLCJpYXQiOjE2NjY1Njk4MDcsImN1c3RvbTpyZWdpc3RlcmVkX2Zyb20iOiJFdmVyeXdoZXJlIiwiZW1haWwiOiJ5dml1bndAeWFuZGV4LmNvbSJ9.GUvpzkp546YUOkGyUy2iIi7Ix--puUISPWXxlIXUVako95QLs9a6g3RmrEjwpMTKJrYqvVeLnXVXsCtQNalSC67N1US4kr8IiR5BhNpflXoLBX0plOprb5cROEqRg9wj6FSDD7I8ZRasa3cCbrb8f2MeaucX41AiWdkBBbtfMJNSfZ_g5sMGsaflMbcQjqEHTRTQ1kpusEAlnxFRmX4XIM0Eame99rg44ZM48E_uHLrbsNR612sECJvTDfVlzI_B4c-Dj25dEqdxWGB0lQ_tjlYbVDneHF9nhQp_QPLdtEUIl7X6k5Gq7rRIFaFi-AMpws5Bz8cWTAsqMz1U9u9f3g","RefreshToken":"eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAifQ.eD-IDDBp9fWw-0w_hEr6oi6U9aBStZlfphrjRBS99zxYS9Nn-ro4EZuFdoBGttZDvjPbfDmh4a-11nzJp7yQ7HEb1zskdK21-sa_rwY6KmiwtLeOHptnRX76PXZwvgnivW7bStoUsjbuAmyhfsVNyNwUEYDW6te0GCwDtI_GUWlvGdkHBypF5AL8DoVyOz5k7QmXwkagFJQaiIK7cl6jViQ8GObP6-25U_tDVXLBNM3yABg5CgkDBPtzEtgCSdPmEGBsSuP__6u1AE1TPadlIvqgbtIzwwRUg40iGHuaH-Q1bpeB8U7uNBVqhcTp2z29lbJ8yWPdfay6Zv2Avs__zw.FURKYHIiQ6868pNn.ParNAANO04M8PlZ6ZplNdiolRu6wXHx-H0bj6fdHVCPthrEttRX-sxBokV4lrAH7mFQJhhBpx3hckZI_fz9v-4FWdjy6DYgP8Wa24R9YJfbpqceQ9sqwNMp7U1tKXVr4C9ZAEnMIISQyi_heFuBb024hSmEI_dczHir_0fJolbMLLXzgAMOMjyQhnQ1G91uf0qJy0YxpaRIVKHnWDxoMLLarlHy09eyE-lrg8dNQNx2VniOo4NAe8lwwL2K_ZDfqmqyUFnbgooj28UjthU5MVg2EGp4PS3AlBS8G4DCWOyInQ5w5C8pODYndjaEpcGVeg0ODs87ctanWVWGLtIo93AfZ17zvrHSuGduDdTcuHZ5Jl8po1cYECOlHMDs29oIFBhUteqKPYw8kj0Ida47svVrZJellmZcjpA0PrYGiiITPWB08Yed9SP5-Pe38JrZffYG1IJ_q-cDqHYmP4wrZ1po6WfqAkOPKQstjTgPK1zw-m_7JIIAAbEXujH2_J9Cmd-JRGBqNc7bVzm7XYtndZvyCYgCnL9y4TdmaH8L_qxbt5I_jfd8CGRw07IDur-r0MXS-PRMjTwxPPuGGCmTwylW-hmaEb1LFHB4gyTldbYUv7MKIsA2DotvnlM4fm6l7_wIil_deDewkMjgP3Ovf3EIlQHKnwA913kjSNjecXCCX_axb42EVuU3SyAAzHTbA_OUml_UeB2B7rzN8x8B8ip3DRcBCprZeCQ3zJrgJP8rA3cuUKfl981NTZwTjffmsnMly-UZiaY7Lgw5LR9VmXO8TCE4O8OhxXxDZ29Yj8QBpyXbI-fdghiDC1FLipLrwhRSufeHwqbq5nC8MucRxzIz201ZGJe-6WP0sJnZtkPL6T6UKAASMRf5sxKH7YRVIm1pDYrOfRdcnEFTfRCAFSzvlnuSKaY0riujYT1zP-U5of8bH8ujlK4MSYgcWtHqp8cLTIJihSYXQ8xVoCkCoq-8wi4D25qSogagX6vHM0WN5szNMl7BxLSih7XNhXS9LdTDlBK5xr1YBrGktz6AjpoGZ4Zd043iB2duQ1ZGWx6aP2wA4pMCpv1d3WHU7MgeEq2_DMb7kOcZAz-Abl-q5ITwkbDB8X_z3Kt8b48yWwCOywwuNaokTx0zOL92VSQHCb0wRWbghdFcVbBWaX66JLS9h6Dbld3hrgZSwe8ibGGce_cmMABMEpqLgR-GPw5b2-C7O0mwZQmR6xOZ5RdzWpduzS8qaWN6VmlCCgD2ngK7bDcQyGhOqqNdUTB4ZIVJd5HvqcY0_3OPjYCQua1JotH-aVA.Ti_2jm3yHbbIni5uwSK05g","TokenType":"Bearer"},"ChallengeParameters":{}}
`

**Comment by cabiamdos** [comment]
Well my idea was to spoof fiddler checker with my own checker that returns always authenticated & authorized

**Comment by cabiamdos** [comment]
after investigating a little bit I donwloaded v2.2 fiddler from the official page and I found a cracked main.xxx.js on the internet + I modified the other main.js to disable updates, but I get the following error (creating trials is not allowed):

[main.32665250d6a4bcfe032d.js.zip](https://github.com/msojocs/fiddler-everywhere-crack/files/9852961/main.32665250d6a4bcfe032d.js.zip)

[main.zip](https://github.com/msojocs/fiddler-everywhere-crack/files/9852963/main.zip)

this URL to download fiddle version 2.2.0 from the official page (https://iptvapps.net/resources/fiddler-everywhere-2-2-0-crack.137/)

![image](https://user-images.githubusercontent.com/82284393/197565933-acfcf7da-84d4-4214-a8bf-c7c00633ebb5.png)

whatever, my conclusion is that we should modify something in the network or something in the app that directly creates trial without checking in the internet

**Comment by msojocs** [comment]
Sorry.
The current crack method is not suitable for the latest version (v3.4.1).
It needs update.

**Comment by msojocs** [comment]
> this should be the endpoint on the fetch function, howerver when you use this in another js file or postman it always receives 400 bad request.
> 
> ```
> import fetch from "node-fetch";
> 
> const k = {
>   AuthFlow:"USER_PASSWORD_AUTH",ClientId:"34vrraouuamaupd21r16tsb6aq",
>   AuthParameters:{
>     "USERNAME":"emailATgmail.com",
>     "PASSWORD":"yourPassword"
>   },
>   ClientMetadata:{
>     migrationInvokedFromSignin:true,
>     clientId:""
>   }
> }
> 
> fetch('https://cognito-idp.us-east-1.amazonaws.com/', 
>   {
>     headers: {
>       "Content-Type":"application/x-amz-json-1.1",
>       "X-Amz-Target":"AWSCognitoIdentityProviderService.InitiateAuth",
>       "X-Amz-User-Agent":"aws-amplify/0.1.x js"
>     },
>     method:"POST",
>     mode:"cors",
>     cache:"no-cache",
>     body: JSON.stringify(k)
>   }
> ).then(res => {
>   console.log('res', res);
>   res.json()
> })
> .then(data => console.log(data))
> .catch(err => console.log(err));
> ```
> 
> But the response object should be something like this (in the res.json()):
> 
> ```
> // RESPONSE AUTHENTICATION TOKEN
>               // at: {}, je: {"AuthenticationResult":{"AccessToken":"eyJraWQiOiIrYlducUg4bEo3TStcL2x4OTgrZllNbHdtNDFqZVYrOTFEWnZ6WFhnVHNiVT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIzZmIzODk4YS03MGY3LTRlNzYtYTU0Ni1iZjE5YzczNDI3OGIiLCJldmVudF9pZCI6Ijc2NTI2ODM0LWEyMWMtNGI5OS04NTNmLWM5MzJjNzYyMDYxNSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2NjY1Njk4MDcsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX1lwVnlNNFNvciIsImV4cCI6MTY2NjU3MzQwNywiaWF0IjoxNjY2NTY5ODA3LCJqdGkiOiI3ZTY5OTQ0Zi00NWJjLTQ5N2MtYWZlMy04MjA4YjMyYzcyNjciLCJjbGllbnRfaWQiOiIzNHZycmFvdXVhbWF1cGQyMXIxNnRzYjZhcSIsInVzZXJuYW1lIjoieXZpdW53YXR5YW5kZXguY29tIn0.N7DG2m6xVNLwCHLNsiHsf7LEP35rnxbAsf9PNJjevsf2I1IUT5yX0I4_0S7lp0m7o_XdH82FzJ4BeiPEOlo3qLF5QZtyQPbsWc1Y_x0NZB3xEX-Jh_YCgC0KGJQL8pOgRkqKPMBgYey1X6c-PkYIp9lhKs5CC96aFJakVbCCHKe0kgzqL4yo3TWWbZVTjYfxdeeCHEh3wbpzLGX3_lGi7z2lclpoGKaAzrVL6u9vYcxZyY9t8tlaQ_Ai88bocvbENmL3FmIZxUXrHcd094Qnx6B1GpvOV1OijhEgOiFqoxHqQEl4Rtg1cOA7U_rx0Gx2GIW6px6xiyaLfNBcrH5R1g","ExpiresIn":3600,"IdToken":"eyJraWQiOiJ1OHJCdTE2eDYrTUlHQkJUS2JwXC9GTmw0bW4zMkdLMUtmeU5pZGxhc3pxQT0iLCJhbGciOiJSUzI1NiJ9.eyJjdXN0b206Y291bnRyeSI6IlNwYWluIiwic3ViIjoiM2ZiMzg5OGEtNzBmNy00ZTc2LWE1NDYtYmYxOWM3MzQyNzhiIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImN1c3RvbTpldmVyeXdoZXJlX2V1bGEiOiIzLjIuMCIsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX1lwVnlNNFNvciIsImN1c3RvbTptYXJrZXRpbmdfb3B0ZWQiOiJubyIsImNvZ25pdG86dXNlcm5hbWUiOiJ5dml1bndhdHlhbmRleC5jb20iLCJjdXN0b206c3RhdGUiOiJOVUxMIiwiY3VzdG9tOmNvbXBhbnkiOiJOQU4iLCJhdWQiOiIzNHZycmFvdXVhbWF1cGQyMXIxNnRzYjZhcSIsImN1c3RvbTpsYXN0X25hbWUiOiJOb3NlIiwiZXZlbnRfaWQiOiI3NjUyNjgzNC1hMjFjLTRiOTktODUzZi1jOTMyYzc2MjA2MTUiLCJjdXN0b206Zmlyc3RfbmFtZSI6IlJvYmVydCIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNjY2NTY5ODA3LCJjdXN0b206cGhvbmVfbnVtYmVyIjoiNjY0ODI5MjAzIiwiZXhwIjoxNjY2NTczNDA3LCJjdXN0b206cm9sZSI6IlN0dWRlbnQiLCJpYXQiOjE2NjY1Njk4MDcsImN1c3RvbTpyZWdpc3RlcmVkX2Zyb20iOiJFdmVyeXdoZXJlIiwiZW1haWwiOiJ5dml1bndAeWFuZGV4LmNvbSJ9.GUvpzkp546YUOkGyUy2iIi7Ix--puUISPWXxlIXUVako95QLs9a6g3RmrEjwpMTKJrYqvVeLnXVXsCtQNalSC67N1US4kr8IiR5BhNpflXoLBX0plOprb5cROEqRg9wj6FSDD7I8ZRasa3cCbrb8f2MeaucX41AiWdkBBbtfMJNSfZ_g5sMGsaflMbcQjqEHTRTQ1kpusEAlnxFRmX4XIM0Eame99rg44ZM48E_uHLrbsNR612sECJvTDfVlzI_B4c-Dj25dEqdxWGB0lQ_tjlYbVDneHF9nhQp_QPLdtEUIl7X6k5Gq7rRIFaFi-AMpws5Bz8cWTAsqMz1U9u9f3g","RefreshToken":"eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAifQ.eD-IDDBp9fWw-0w_hEr6oi6U9aBStZlfphrjRBS99zxYS9Nn-ro4EZuFdoBGttZDvjPbfDmh4a-11nzJp7yQ7HEb1zskdK21-sa_rwY6KmiwtLeOHptnRX76PXZwvgnivW7bStoUsjbuAmyhfsVNyNwUEYDW6te0GCwDtI_GUWlvGdkHBypF5AL8DoVyOz5k7QmXwkagFJQaiIK7cl6jViQ8GObP6-25U_tDVXLBNM3yABg5CgkDBPtzEtgCSdPmEGBsSuP__6u1AE1TPadlIvqgbtIzwwRUg40iGHuaH-Q1bpeB8U7uNBVqhcTp2z29lbJ8yWPdfay6Zv2Avs__zw.FURKYHIiQ6868pNn.ParNAANO04M8PlZ6ZplNdiolRu6wXHx-H0bj6fdHVCPthrEttRX-sxBokV4lrAH7mFQJhhBpx3hckZI_fz9v-4FWdjy6DYgP8Wa24R9YJfbpqceQ9sqwNMp7U1tKXVr4C9ZAEnMIISQyi_heFuBb024hSmEI_dczHir_0fJolbMLLXzgAMOMjyQhnQ1G91uf0qJy0YxpaRIVKHnWDxoMLLarlHy09eyE-lrg8dNQNx2VniOo4NAe8lwwL2K_ZDfqmqyUFnbgooj28UjthU5MVg2EGp4PS3AlBS8G4DCWOyInQ5w5C8pODYndjaEpcGVeg0ODs87ctanWVWGLtIo93AfZ17zvrHSuGduDdTcuHZ5Jl8po1cYECOlHMDs29oIFBhUteqKPYw8kj0Ida47svVrZJellmZcjpA0PrYGiiITPWB08Yed9SP5-Pe38JrZffYG1IJ_q-cDqHYmP4wrZ1po6WfqAkOPKQstjTgPK1zw-m_7JIIAAbEXujH2_J9Cmd-JRGBqNc7bVzm7XYtndZvyCYgCnL9y4TdmaH8L_qxbt5I_jfd8CGRw07IDur-r0MXS-PRMjTwxPPuGGCmTwylW-hmaEb1LFHB4gyTldbYUv7MKIsA2DotvnlM4fm6l7_wIil_deDewkMjgP3Ovf3EIlQHKnwA913kjSNjecXCCX_axb42EVuU3SyAAzHTbA_OUml_UeB2B7rzN8x8B8ip3DRcBCprZeCQ3zJrgJP8rA3cuUKfl981NTZwTjffmsnMly-UZiaY7Lgw5LR9VmXO8TCE4O8OhxXxDZ29Yj8QBpyXbI-fdghiDC1FLipLrwhRSufeHwqbq5nC8MucRxzIz201ZGJe-6WP0sJnZtkPL6T6UKAASMRf5sxKH7YRVIm1pDYrOfRdcnEFTfRCAFSzvlnuSKaY0riujYT1zP-U5of8bH8ujlK4MSYgcWtHqp8cLTIJihSYXQ8xVoCkCoq-8wi4D25qSogagX6vHM0WN5szNMl7BxLSih7XNhXS9LdTDlBK5xr1YBrGktz6AjpoGZ4Zd043iB2duQ1ZGWx6aP2wA4pMCpv1d3WHU7MgeEq2_DMb7kOcZAz-Abl-q5ITwkbDB8X_z3Kt8b48yWwCOywwuNaokTx0zOL92VSQHCb0wRWbghdFcVbBWaX66JLS9h6Dbld3hrgZSwe8ibGGce_cmMABMEpqLgR-GPw5b2-C7O0mwZQmR6xOZ5RdzWpduzS8qaWN6VmlCCgD2ngK7bDcQyGhOqqNdUTB4ZIVJd5HvqcY0_3OPjYCQua1JotH-aVA.Ti_2jm3yHbbIni5uwSK05g","TokenType":"Bearer"},"ChallengeParameters":{}}
> ```

Thanks for what you have done.

**Comment by RootEncrypter** [comment]
@cabiamdos @msojocs any update or new crack for this? Please let me know

**Comment by msojocs** [comment]
> @cabiamdos @msojocs any update or new crack for this? Please let me know

latest files were pushed.

**Comment by RootEncrypter** [comment]
Works for windows too now. Thank you. Could you push the file to not update the file?

**Comment by londek** [comment]
Welcome sir, 3.4.1 still doesn't work for me
![image](https://user-images.githubusercontent.com/48859717/200144554-c64a474a-fb2f-4b39-92c0-46638879cc48.png)

I've tried logging in from both aged and fresh accounts, from basic RE it looks like `currentLicense` should be an object, not a `string` (atleast in order to eliminate exception shown in screen). There are no XHR errors, all requests are 200, Fiddler is pulling out tokens from cognito correctly. I've tried manually editing files and have used yours, but neither option succeed. Could you please send me `JSON.stringify` of your `currentLicense` so I can try to replace mine? Thanks

**Comment by msojocs** [comment]
> Welcome sir, 3.4.1 still doesn't work for me ![image](https://user-images.githubusercontent.com/48859717/200144554-c64a474a-fb2f-4b39-92c0-46638879cc48.png)
> 
> I've tried logging in from both aged and fresh accounts, from basic RE it looks like `currentLicense` should be an object, not a `string` (atleast in order to eliminate exception shown in screen). There are no XHR errors, all requests are 200, Fiddler is pulling out tokens from cognito correctly. I've tried manually editing files and have used yours, but neither option succeed. Could you please send me `JSON.stringify` of your `currentLicense` so I can try to replace mine? Thanks

![image](https://user-images.githubusercontent.com/20937135/200149551-979eba40-b07a-4df6-a376-be2908f8db7a.png)

```javascript
{
    "email": "jijijiji@gmail.com",
    "localUserDirName": "a3da312d1efc2e038d6cc3641a181d2294c1684aeafc796ab2de7ef78a017488",
    "username": "jiyecafe",
    "name": "ji ye",
    "picture": "https://lh3.googleusercontent.com/a/ALm5wu3VHkLjNNecoJblVvF2x6nJdUXDjMCpIW3O04FF=s96-c",
    "accessToken": "replace with token",
    "idToken": "replace with token",
    "userId": "replace with id",
    "userMigrationInfo": null,
    "hasAcceptedEula": true,
    "isLoginCompleted": true,
    "requiresPiiConsent": true,
    "hasInitializedTheApp": true,
    "isInOutOfSupportVersion": false,
    "licenseInfo": {
        "currentLicense": {
            "name": "Trial",
            "expiresAfter": -494,
            "quotas": [
                {
                    "value": 0,
                    "max": 1000,
                    "maxDisplayString": "1000",
                    "type": "Shared Sessions"
                },
                {
                    "value": 0,
                    "max": 2147483647,
                    "maxDisplayString": "unlimited",
                    "type": "Shared Requests"
                },
                {
                    "value": 0,
                    "max": 2147483647,
                    "maxDisplayString": "unlimited",
                    "type": "SharedRuleSets"
                },
                {
                    "value": 0,
                    "max": 2147483647,
                    "maxDisplayString": "unlimited",
                    "type": "SnapshotSharedWithUsers"
                },
                {
                    "value": 0,
                    "max": 2147483647,
                    "maxDisplayString": "unlimited",
                    "type": "LocalSnapshots"
                },
                {
                    "value": 0,
                    "max": 2147483647,
                    "maxDisplayString": "unlimited",
                    "type": "RuleSetSharedWithUsers"
                },
                {
                    "value": 0,
                    "max": 2147483647,
                    "maxDisplayString": "unlimited",
                    "type": "LocalAutoResponderRules"
                }
            ],
            "isManuallyRequested": false
        },
        "isTrialAvailable": false,
        "canPurchase": true,
        "hasValidLicense": true,
        "hasExpiredTrial": true,
        "isOwnerWithoutSeat": false,
        "licensePlanPeriod": "unknown"
    },
    "createdAt": "2021-02-18T09:06:02.899Z"
}
```

**Comment by londek** [comment]
I've realized I also have 3.2.1 installer, tho 3.2.1 doesn't work for me too, I also tried making new accs to see if I can redeem trial, but no I can't, I guess there is some error in electron backend/fiddler webserver backend. It has to be something specific to my pc, I don't really know what, but I'm gonna re a bit to understand program flow a little bit better. Best regards

**Comment by londek** [comment]
I have resolved my issues by adding
```
Ce.isLoginCompleted = true;
Ce.hasInitializedTheApp = true;
Ce.requiresPiiConsent = false;
```
I didn't find root cause, but it's something about amplify subscribers not being notified + Electron being electron (lol) at the same time.

**Comment by londek** [comment]
I've found the root problem being HWID - here are ways they gather machine ids, so you can fix it for yourself too if you get blacklisted:
```
darwin: ioreg -rd1 -c IOPlatformExpertDevice
win32: REG.exe QUERY HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Cryptography /v MachineGuid
linux: ( cat /var/lib/dbus/machine-id /etc/machine-id 2> /dev/null || hostname ) | head -n 1 || :
freebsd: kenv -q smbios.system.uuid || sysctl -n kern.hostuuid
```
Hope my research helped, also please consider adding this to `DETAIL.MD`
Thanks

**Comment by fertuter22** [comment]
> Welcome sir, 3.4.1 still doesn't work for me ![image](https://user-images.githubusercontent.com/48859717/200144554-c64a474a-fb2f-4b39-92c0-46638879cc48.png)
> 
> I've tried logging in from both aged and fresh accounts, from basic RE it looks like `currentLicense` should be an object, not a `string` (atleast in order to eliminate exception shown in screen). There are no XHR errors, all requests are 200, Fiddler is pulling out tokens from cognito correctly. I've tried manually editing files and have used yours, but neither option succeed. Could you please send me `JSON.stringify` of your `currentLicense` so I can try to replace mine? Thanks

hi
sorry for stupid question but i wondering what is this console like in browser on the rightside of your screenshot? how can i get it too? is it possible to make with any programm? :)

**Comment by pjy612** [comment]
If you convert the Trial license, you should be able to use all the features, but if you don't have a Trial license at all, you will only be able to use the local features.
