### ISSUE TITLE
Version 5.17.0 resources\app\out\WebServer\ClientApp\dist 中没有main.5f4387a481528ff0.js文件

### ISSUE THREAD

**Issue by VincentVanNF** [msojocs/fiddler-everywhere-enhance#71]
![image](https://github.com/user-attachments/assets/a02532ef-4fb3-4196-a3b0-859ec1f216eb)

**Comment by sipsuru** [comment]
Well, the name `main.5f4387a481528ff0.js` is from an very old version and even in `V 5.15.1` the `js`s are not named like that with numbers. I assume you're new to this patch/crack.

In never versions of Fiddler Everywhere,  these `js`s are named with letters not numbers. so `main.QDNQBNPT.js` is the file you're looking for. 

But there seems to be a bigger problem: See #72
