### ISSUE TITLE
No libfiddler.dll Anymore | Not Compatible with 5.17.0 | Seems Broken for 5.15 + 

### ISSUE THREAD

**Issue by sipsuru** [msojocs/fiddler-everywhere-enhance#72]
**There's no `libfiddler.dll` file anymore (I checked in v 5.17.0).**

![No `libfiddler.dll`](https://github.com/user-attachments/assets/08e8f4a7-d3b3-429a-bee5-c49645f708b4)

**Of course there's a `dll` named `fiddler.dll`**

![Have `fiddler.dll` instead](https://github.com/user-attachments/assets/e6c22080-af94-4098-87a5-015867d8bb05)

Know somewhat dumb but tried following fixes
  - I didn't delete `fiddler.dll` and copied `libfiddler.dll` from Yukihana-Patch and applied other patches. Didn't work. Didn't even show loading UI
  - I deleted `fiddler.dll` and copied `libfiddler.dll` and applied other patches. Didn't work either.
  - Delered `fiddler.dll` and copied `libfiddler.dll` but also renamed `libfiddler.dll` to `fiddler.dll`. Didn't work either.
  
 Well, I know doing these kind of things is just **dumb** but I still did in case that only the dll name is changed. But it's not.
 
 
**Apparently the `size` of the dlls `libfiddler.dll` from Fiddler Everywhere 5.15.1 and `fiddler.dll` from 5.17.0 **does not** have a significant change in size. Actually it's a 1KB**
 
 
![Fiddler Everywhere 5.15.1 - Works](https://github.com/user-attachments/assets/8e6e7ae1-dbc8-4f2b-a1a9-2efa8f033793)

![Fiddler Everywhere 5.17.0 - Doesn't Work](https://github.com/user-attachments/assets/1cdb71d4-0219-492a-81b0-035bb2da10a3)

Additional: Cuz there's no official way to get old releases, and as the newest release isn't compatible (as I see). I'll leave a download link for 5.15.1. This's the latest version I checked with the patch. Don't know if any never version is compatible with. [Download it](https://www.dropbox.com/scl/fi/pq8ekck12vu7l939b8w2r/Fiddler-Everywhere-5.15.1.exe?rlkey=0cv1g4r9t4q90qq436qauhos7&st=dkr4906a&dl=1)

**Comment by msojocs** [comment]
Thanks, I will check it.

**Comment by msojocs** [comment]
https://github.com/project-yukihana/Yukihana-patch/releases/tag/continuous

pls try this version.

**Comment by sipsuru** [comment]
Oh, it works. Tnx.

**Comment by yudehai0204** [comment]
> Oh, it works. Tnx.

hello, I know fiddler.dll and hostpolicy.dll  replace target file, but Which directory does dbghelp replace
?
