### ISSUE TITLE
Server doesn't start due to unknown reasons. Seems device specific though. Not version specific. [5.9.0 - 5.18.0]

### ISSUE THREAD

**Issue by sipsuru** [msojocs/fiddler-everywhere-enhance#75]
Some reported that the `server` is not up after patching correctly. I couldn't figure out the actual reasons. 
 - Milestone: https://github.com/sipsuru/fiddler-everywhere-patch-automated/milestone/1
 
 > [!NOTE]
 > [These patches](https://github.com/cstnxx/fiddler-everywhere-patch-automated/actions) are reported not working and throwing `Access Violation` in [this issue](https://github.com/sipsuru/fiddler-everywhere-patch-automated/issues/7). But they works fine for others. 

There's no way that the error[s] are caused by incorrect patching, (as patched by automated-patcher).

Could something (IDK but something like a dependancy that require specific / additional permissions or something like that) from `server` cause this error in `specific` systems or environments ? 

Or is it a given that the error must be related to the system not `server`. (I too think this could not be related to the `server` though.) ?

**Comment by msojocs** [comment]
It looks like the user didn't replace the file correctly.

**Comment by sipsuru** [comment]
It's patched by [automated patching](https://github.com/sipsuru/fiddler-everywhere-patch-automated) !?

But seems like device specific though. No work needed. 😊

**Comment by sipsuru** [comment]
Question: Is there any paticular reason for removing `fiddler.dll` and `hostpolicy.dll` from `Yukihana-Patch 1.1.1` ?

**Comment by msojocs** [comment]
> QUIZ: Is there any paticular reason for removing `fiddler.dll` and `hostpolicy.dll` from `Yukihana-Patch 1.1.1` ?
> 
> [ Well, they automated patching can't automatically select a version for patching now. I'd to manually set `1.1.0` instead of `continuous`. 😕]

emmm....maybe, it is bug😂

**Comment by sipsuru** [comment]
> Some reported that the `server` is not up after patching correctly. I couldn't figure out the actual reasons.
> 
> * Milestone: https://github.com/sipsuru/fiddler-everywhere-patch-automated/milestone/1
> 
> Note
> 
> [These patches](https://github.com/cstnxx/fiddler-everywhere-patch-automated/actions) are reported not working and throwing `Access Violation` in [this issue](https://github.com/sipsuru/fiddler-everywhere-patch-automated/issues/7). But they works fine for others.
> 
> There's no way that the error[s] are caused by incorrect patching, (as patched by automated-patcher).
> 
> Could something (IDK but something like a dependancy that require specific / additional permissions or something like that) from `server` cause this error in `specific` systems or environments ?
> 
> Or is it a given that the error must be related to the system not `server`. (I too think this could not be related to the `server` though.) ?

Could be this:
---------------

You need to check if this happens **WITHOUT Patch**. Means you need to try install and open Fiddler Everywhere Official non-patched version.

In [Fiddler Everywhere  Documentation -> Prerequiements](https://docs.telerik.com/fiddler-everywhere/installation-and-setup/quickstart-windows#prerequisites); it says:
> Ensure that Fiddler Everywhere's proxy port is open and unrestricted by a firewall/security tool. The default port is 8866, but you can change it from Settings > Connections > Fiddler listens on port.

It seems like Fiddler Everywhere's proxy port is restricted by any of your security/firewall tool.  
(It doesn't seems to be closed/already-in-use port error because every port it tries fails.)

Again; un-related to Patch.


---


你需要检查这是否在未打补丁的情况下发生。这意味着你需要尝试安装并打开官方的未打补丁版本的 Fiddler Everywhere。

在 [Fiddler Everywhere 文档 -> 先决条件](https://docs.telerik.com/fiddler-everywhere/installation-and-setup/quickstart-windows#prerequisites) 中提到：

> 确保 Fiddler Everywhere 的代理端口是开放的，且未被防火墙/安全工具限制。默认端口是 8866，但你可以在设置 > 连接 > Fiddler 监听的端口中进行更改。

看起来 Fiddler Everywhere 的代理端口被某些安全工具或防火墙限制了。
（这似乎并不是端口关闭或已被占用的错误，因为每个尝试的端口都失败了。）

再次强调，这与补丁无关。
