### ISSUE TITLE
FiddlerEverywhere 3.4.1 的版本支持该方式吗？

### ISSUE THREAD

**Issue by rich1e** [msojocs/fiddler-everywhere-enhance#8]
FiddlerEverywhere Version: 3.4.1
OS System: macOS Big Sur 11.7
CPU type: M1

搜索 `mainXXX.js` 文件，发现有3个 `updateUserLicense` 关键字，请问应该插入哪个位置？

![image](https://user-images.githubusercontent.com/29914689/196156915-4fee8981-e911-4e5b-bcc1-d4b0142796d6.png)

**Comment by msojocs** [comment]
https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD

请尝试查看此链接内容

**Comment by msojocs** [comment]
请问问题是否已解决？

**Comment by rich1e** [comment]
还没有。

我常用的电脑是mac，预处理那部分，不好解决。

- 准备好 ildasm 与 ilasm
- 使用 ildasm 将 Fiddler.WebUi.dll 转换为 il 文件
- 使用 ildasm 将 FiddlerBackendSDK.dll 转换为 il 文件

执行 `ilasm` 报错显示：`zsh: exec format error: ilasm`。下列为安装信息和错误截图。

![](https://user-images.githubusercontent.com/29914689/196884371-23f3cd40-a71c-4cd7-aba2-228f36aac518.png)

![](https://user-images.githubusercontent.com/29914689/196884263-55cdcb8f-db9f-4e74-9754-97b2db38ff07.png)

![](https://user-images.githubusercontent.com/29914689/196884450-27e0df48-88ea-419d-a5c6-e12a95d4297c.png)

![](https://user-images.githubusercontent.com/29914689/196884190-a1c32b3a-732d-4fa3-b442-ccb9bee2f5a6.png)

**Comment by rich1e** [comment]
ilasm 文件生成了，但在mac下不可以运行。

![image](https://user-images.githubusercontent.com/29914689/196885760-1fb2f26a-e8a7-4331-9acb-9a0531cfd31b.png)

**Comment by msojocs** [comment]
我没有mac，所以只能提供参考：
`dotnet publish -c Release --self-contained --runtime linux-x64`
这个runtime应该要修改为mac对应的值 `osx-x64` (不确定是否可用)

**Comment by msojocs** [comment]
方法暂不支持3.4.1，缺少一些操作，还在研究。

**Comment by rich1e** [comment]
> 方法暂不支持3.4.1，缺少一些操作，还在研究。

Mac 平台编译后的 ildasm 和 ilasm，命令跟平常不太一样吧？

使用管道命令获取 `il` 文件：

```shell
ildasm Fiddler.WebUi.dll > Fiddler.WebUi.il
```

但是反编译后的[文件代码](https://github.com/msojocs/fiddler-everywhere-crack/files/9867356/code.zip)与文档有些不一样，能否帮忙看看？

**Comment by msojocs** [comment]
> 方法暂不支持3.4.1，缺少一些操作，还在研究。

收回前话，仍然可用

**Comment by Wrong-pixel** [comment]
FiddlerEverywhere Version: 3.4.1
OS System: macOS Big Sur 13.0
CPU type: M1 Pro

修改完il文件后使用ilasm重新编译dll文件时出现warning，如下：
```
Fiddler.WebUi.il(13309) : warning : Duplicate param name '_' in method '<GetPasswordDelegateWithoutPrompt>b__0'
Fiddler.WebUi.il(13358) : warning : Duplicate param name '_' in method '<GetPasswordDelegateWithMaxAttempts>b__0'
```
并且替换dll后Fiddler出现闪退，由于截图不全，我是将`Fiddler.WebUi.il`文件中两个函数的.try内容删除，直到stind.ref
<img width="855" alt="image" src="https://user-images.githubusercontent.com/43137902/198953152-72eb67d3-3717-4b1c-b2e4-634dfb278aa2.png">
<img width="826" alt="image" src="https://user-images.githubusercontent.com/43137902/198953189-9aaffd4e-efa8-4bc3-b205-eb59ceade0c5.png">
不知道是不是il文件修改错误呢？如果不是的话可能是macos13的兼容性问题，我尚未在macos11上测试

**Comment by Wrong-pixel** [comment]
> 

将.net版本由7.0更换为6.0以后不再闪退，但是提示APP已损坏，执行xattr 命令清除 app 的隔离属性后打开仍然闪退

**Comment by rich1e** [comment]
非常感谢，晚点我在本地试试。

有个问题请教一下，il文件的代码实在看不懂，修改代码部分还是参考这个[文档](https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD)吗？

**Comment by Wrong-pixel** [comment]
> 非常感谢，晚点我在本地试试。
> 
> 有个问题请教一下，il文件的代码实在看不懂，修改代码部分还是参考这个[文档](https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD)吗？

使用.net6.0以后成功了，修改代码部分就是参考文档，目前系统macos 13.0可以正常运行

**Comment by tuan6956** [comment]
> > Cảm ơn rất nhiều, tôi sẽ thử nó tại địa phương sau.
> > Mình có một thắc mắc muốn hỏi, phần code của file il thật sự không hiểu được, mình có nên tham khảo [tài liệu](https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD) này để sửa lại phần code không?
> 
> Sau khi sử dụng .net6.0 thành công, phần code đã sửa đổi là tài liệu tham khảo, hiện tại hệ thống macos 13.0 có thể chạy bình thường

你能逐步描述一下macos吗？ 我正在使用 M1

**Comment by tuan6956** [comment]
> > 非常感谢，晚点我在本地试试。
> > 有个问题请教一下，il文件的代码实在看不懂，修改代码部分还是参考这个[文档](https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD)吗？
> 
> 使用.net6.0以后成功了，修改代码部分就是参考文档，目前系统macos 13.0可以正常运行

你能逐步描述一下macos吗？ 我正在使用 M1

**Comment by Wrong-pixel** [comment]
> > > 非常感谢，晚点我在本地试试。
> > > 有个问题请教一下，il文件的代码实在看不懂，修改代码部分还是参考这个[文档](https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD)吗？
> > 
> > 
> > 使用.net6.0以后成功了，修改代码部分就是参考文档，目前系统macos 13.0可以正常运行
> 
> 你能逐步描述一下macos吗？ 我正在使用 M1

大部分内容都是参考[此文档](https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD)，但是有一点忘记声明了，我于3.4.1失败后降级至3.4.0，并且在windows虚拟机中使用dnspy.net修改dll

**Comment by rich1e** [comment]
> FiddlerEverywhere Version: 3.4.1 OS System: macOS Big Ventura 13.0 CPU type: M1 Pro
> 
> 修改完il文件后使用ilasm重新编译dll文件时出现warning，如下：
> 
> ```
> Fiddler.WebUi.il(13309) : warning : Duplicate param name '_' in method '<GetPasswordDelegateWithoutPrompt>b__0'
> Fiddler.WebUi.il(13358) : warning : Duplicate param name '_' in method '<GetPasswordDelegateWithMaxAttempts>b__0'
> ```
> 
> 并且替换dll后Fiddler出现闪退，由于截图不全，我是将`Fiddler.WebUi.il`文件中两个函数的.try内容删除，直到stind.ref <img alt="image" width="855" src="https://user-images.githubusercontent.com/43137902/198953152-72eb67d3-3717-4b1c-b2e4-634dfb278aa2.png"> <img alt="image" width="826" src="https://user-images.githubusercontent.com/43137902/198953189-9aaffd4e-efa8-4bc3-b205-eb59ceade0c5.png"> 不知道是不是il文件修改错误呢？如果不是的话可能是macos13的兼容性问题，我尚未在macos11上测试

Mac 中你是用什么命令编译dll呢？

```sh
ilasm Fiddler.WebUi.il /dll /output:Fiddler.WebUi.dll
```
我使用这个命令，一直失败，也没找到相关文档。
![image](https://user-images.githubusercontent.com/29914689/199465353-dfd89449-a183-441a-a475-e9f5e19a9129.png)

**Comment by tuan6956** [comment]
> > > > 非常感谢，晚点我在本地试试。
> > > > 有个问题请教一下，il文件的代码实在看不懂，修改代码部分还是参考这个[文档](https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD)吗？
> > > 
> > > 
> > > 使用.net6.0以后成功了，修改代码部分就是参考文档，目前系统macos 13.0可以正常运行
> > 
> > 
> > 你能逐步描述一下macos吗？ 我正在使用 M1
> 
> 大部分内容都是参考[此文档](https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD)，但是有一点忘记声明了，我于3.4.1失败后降级至3.4.0，并且在windows虚拟机中使用dnspy.net修改dll

我已经尝试过并且失败了。 在按照作者描述的步骤之前是否需要登录？

**Comment by Wrong-pixel** [comment]
> 

在没有使用dnspy之前，我用的`ilasm FiddlerBackendSDK.il > FiddlerBackendSDK.dll`进行汇编，我不确定这是不是正确的方式，但我用此方式能生成dll文件。如果实在不行，[这里](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1679610&highlight=fiddler%2B3.4.0)有修改完成的3.4.0的dll文件，但安全性未验证

**Comment by Wrong-pixel** [comment]
> > FiddlerEverywhere Version: 3.4.1
> > OS System: macOS Big Ventura 13.0
> > CPU type: M1 Pro
> > 修改完il文件后使用ilasm重新编译dll文件时出现warning，如下：
> > ```
> > Fiddler.WebUi.il(13309) : warning : Duplicate param name '_' in method '<GetPasswordDelegateWithoutPrompt>b__0'
> > Fiddler.WebUi.il(13358) : warning : Duplicate param name '_' in method '<GetPasswordDelegateWithMaxAttempts>b__0'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 并且替换dll后Fiddler出现闪退，由于截图不全，我是将`Fiddler.WebUi.il`文件中两个函数的.try内容删除，直到stind.ref <img alt="image" width="855" src="https://user-images.githubusercontent.com/43137902/198953152-72eb67d3-3717-4b1c-b2e4-634dfb278aa2.png"> <img alt="image" width="826" src="https://user-images.githubusercontent.com/43137902/198953189-9aaffd4e-efa8-4bc3-b205-eb59ceade0c5.png"> 不知道是不是il文件修改错误呢？如果不是的话可能是macos13的兼容性问题，我尚未在macos11上测试
> 
> @Wrong-pixel Mac 中你是用什么命令编译dll呢？
> 
> ```shell
> ilasm Fiddler.WebUi.il /dll /output:Fiddler.WebUi.dll
> ```
> 
> 我使用这个命令，一直失败，也没找到相关文档。
> 
> ![image](https://user-images.githubusercontent.com/29914689/199465353-dfd89449-a183-441a-a475-e9f5e19a9129.png)

在没有使用dnspy之前，我用的ilasm FiddlerBackendSDK.il > FiddlerBackendSDK.dll进行汇编，我不确定这是不是正确的方式，但我用此方式能生成dll文件。如果实在不行，[这里](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1679610&highlight=fiddler%2B3.4.0)有修改完成的3.4.0的dll文件，但安全性未验证

**Comment by Wrong-pixel** [comment]
> 

不需要登录，操作完成后正常注册登录即可，会将试用时间锁定为一天，如果关闭了自动更新，就可以一直使用该版本。如果实在不行，[这里](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1679610&highlight=fiddler%2B3.4.0)有别人修改好的dll和js文件，但安全性尚未验证，可以用作参考

**Comment by Wrong-pixel** [comment]
> > > > > 非常感谢，晚点我在本地试试。
> > > > > 有个问题请教一下，il文件的代码实在看不懂，修改代码部分还是参考这个[文档](https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD)吗？
> > > > 
> > > > 
> > > > 使用.net6.0以后成功了，修改代码部分就是参考文档，目前系统macos 13.0可以正常运行
> > > 
> > > 
> > > 你能逐步描述一下macos吗？ 我正在使用 M1
> > 
> > 
> > 大部分内容都是参考[此文档](https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD)，但是有一点忘记声明了，我于3.4.1失败后降级至3.4.0，并且在windows虚拟机中使用dnspy.net修改dll
> 
> 我已经尝试过并且失败了。 在按照作者描述的步骤之前是否需要登录？

不需要登录，操作完成后正常注册登录即可，会将试用时间锁定为一天，如果关闭了自动更新，就可以一直使用该版本。如果实在不行，[这里](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1679610&highlight=fiddler%2B3.4.0)有别人修改好的dll和js文件，但安全性尚未验证，可以用作参考

**Comment by rich1e** [comment]
@Wrong-pixel 参考你的回复，本地验证了命令，可以生成dll。但是生成过程报错，估计是删除的代码不对。

```sh
ilasm Fiddler.WebUi.il > Fiddler.WebUi.dll
```

![image](https://user-images.githubusercontent.com/29914689/199661745-008a88fd-fd0c-4b02-a8ee-09646d677d46.png)

@msojocs 参考[该文档](https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD) ，修改了：

- Fiddler.WebUi.il
- FiddlerBackendSDK.il

 但是生成的dll有问题，能帮忙看看这个代码该如何修改？

![](https://user-images.githubusercontent.com/29914689/199664956-2eca1b86-5a0b-4f75-bb1f-6a2ae9050e71.png)

[这是 dll 转换后的 il 文件](https://github.com/msojocs/fiddler-everywhere-crack/files/9926188/code.zip)（3.4.1 版本 ）

[这是我自己修改的 il 文件](https://github.com/msojocs/fiddler-everywhere-crack/files/9926200/code2.zip)

**Comment by tuan6956** [comment]
windows

> > > > > > 非常感谢，晚点我在本地试试。
> > > > > > 有个问题请教一下，il文件的代码实在看不懂，修改代码部分还是参考这个[文档](https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD)吗？
> > > > > 
> > > > > 
> > > > > 使用.net6.0以后成功了，修改代码部分就是参考文档，目前系统macos 13.0可以正常运行
> > > > 
> > > > 
> > > > 你能逐步描述一下macos吗？ 我正在使用 M1
> > > 
> > > 
> > > 大部分内容都是参考[此文档](https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD)，但是有一点忘记声明了，我于3.4.1失败后降级至3.4.0，并且在windows虚拟机中使用dnspy.net修改dll
> > 
> > 
> > 我已经尝试过并且失败了。 在按照作者描述的步骤之前是否需要登录？
> 
> 不需要登录，操作完成后正常注册登录即可，会将试用时间锁定为一天，如果关闭了自动更新，就可以一直使用该版本。如果实在不行，[这里](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1679610&highlight=fiddler%2B3.4.0)有别人修改好的dll和js文件，但安全性尚未验证，可以用作参考

你能帮我获得下载链接吗，我不是来自中国，也没有上述网站的帐户。 非常感谢

**Comment by tuan6956** [comment]
<img width="1723" alt="image" src="https://user-images.githubusercontent.com/20284059/199682343-17089148-7f48-4694-94ee-1bb76f2cc603.png">
请等待屏幕连续运行而不进入主界面。 你遇到过这个问题吗？

**Comment by Wrong-pixel** [comment]
> > > > > > 非常感谢，晚点我在本地试试。
> > > > > > 有个问题请教一下，il文件的代码实在看不懂，修改代码部分还是参考这个[文档](https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD)吗？
> > > > > 
> > > > > 
> > > > > 使用.net6.0以后成功了，修改代码部分就是参考文档，目前系统macos 13.0可以正常运行
> > > > 
> > > > 
> > > > 你能逐步描述一下macos吗？ 我正在使用 M1
> > > 
> > > 
> > > 大部分内容都是参考[此文档](https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD)，但是有一点忘记声明了，我于3.4.1失败后降级至3.4.0，并且在windows虚拟机中使用dnspy.net修改dll
> > 
> > 
> > 我已经尝试过并且失败了。 在按照作者描述的步骤之前是否需要登录？
> 
> 不需要登录，操作完成后正常注册登录即可，会将试用时间锁定为一天，如果关闭了自动更新，就可以一直使用该版本。如果实在不行，[这里](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1679610&highlight=fiddler%2B3.4.0)有别人修改好的dll和js文件，但安全性尚未验证，可以用作参考

try [this](https://pan.iculture.cc/s/3bgAIP)

**Comment by tuan6956** [comment]
> > > > > > > 非常感谢，晚点我在本地试试。
> > > > > > > 有个问题请教一下，il文件的代码实在看不懂，修改代码部分还是参考这个[文档](https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD)吗？
> > > > > > 
> > > > > > 
> > > > > > 使用.net6.0以后成功了，修改代码部分就是参考文档，目前系统macos 13.0可以正常运行
> > > > > 
> > > > > 
> > > > > 你能逐步描述一下macos吗？ 我正在使用 M1
> > > > 
> > > > 
> > > > 大部分内容都是参考[此文档](https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD)，但是有一点忘记声明了，我于3.4.1失败后降级至3.4.0，并且在windows虚拟机中使用dnspy.net修改dll
> > > 
> > > 
> > > 我已经尝试过并且失败了。 在按照作者描述的步骤之前是否需要登录？
> > 
> > 
> > 不需要登录，操作完成后正常注册登录即可，会将试用时间锁定为一天，如果关闭了自动更新，就可以一直使用该版本。如果实在不行，[这里](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1679610&highlight=fiddler%2B3.4.0)有别人修改好的dll和js文件，但安全性尚未验证，可以用作参考
> 
> try [this](https://pan.iculture.cc/s/3bgAIP)

谢谢但是替换了zip 的文件后，损坏，百度后解决后，一直卡在plase wait...

**Comment by Wrong-pixel** [comment]
> > > > > > > > 非常感谢，晚点我在本地试试。
> > > > > > > > 有个问题请教一下，il文件的代码实在看不懂，修改代码部分还是参考这个[文档](https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD)吗？
> > > > > > > 
> > > > > > > 
> > > > > > > 使用.net6.0以后成功了，修改代码部分就是参考文档，目前系统macos 13.0可以正常运行
> > > > > > 
> > > > > > 
> > > > > > 你能逐步描述一下macos吗？ 我正在使用 M1
> > > > > 
> > > > > 
> > > > > 大部分内容都是参考[此文档](https://github.com/msojocs/fiddler-everywhere-crack/blob/master/DETAIL.MD)，但是有一点忘记声明了，我于3.4.1失败后降级至3.4.0，并且在windows虚拟机中使用dnspy.net修改dll
> > > > 
> > > > 
> > > > 我已经尝试过并且失败了。 在按照作者描述的步骤之前是否需要登录？
> > > 
> > > 
> > > 不需要登录，操作完成后正常注册登录即可，会将试用时间锁定为一天，如果关闭了自动更新，就可以一直使用该版本。如果实在不行，[这里](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1679610&highlight=fiddler%2B3.4.0)有别人修改好的dll和js文件，但安全性尚未验证，可以用作参考
> > 
> > 
> > try [this](https://pan.iculture.cc/s/3bgAIP)
> 
> 谢谢但是替换了zip 的文件后，损坏，百度后解决后，一直卡在plase wait...

抱歉，我没有遇到过此问题，但根据论坛的建议，你可以用cleanmymacx或者app cleaner & uninstall等应用将Fiddler完全卸载后再重新安装，接着替换dll，应该可以解决。

**Comment by rich1e** [comment]
@tuan6956 

[fiddler everywhere 3.4.1 crack for win](https://github.com/msojocs/fiddler-everywhere-crack/tree/master/v3.4.1)

**Comment by rich1e** [comment]
## 步骤：

1.先安装 fiddler everywhere 3.4.0；
2.打开 fiddler everywhere，选择试用；
3.关闭 fiddler everywhere，替换 crack 文件；
4.再次打开，没有试用的标志，完美使用；

> 必须保证操作步骤，否则会 crack 失败！

![](https://user-images.githubusercontent.com/29914689/199898464-c145d3aa-668d-47a2-979e-4576ce93dac5.png)

![](https://user-images.githubusercontent.com/29914689/199898374-25d01fa9-5e2e-446f-93b6-14c1ed53f8ce.png)

[crack 文件](https://pan.iculture.cc/s/3bgAIP)，**只对应 3.4.0 版本。**

## FQA

### 如果出现了please wait，可能是因为先crack后联网。 

> 卸载 fiddler everywhere，按照上述步骤重新安装就可以解决。

类似问题：
  - #9
  - #3 

### 如果打开 fiddler everywhere 时遇到“已损坏，无法打开。 您应该将它移到废纸篓”的问题。

打开【启动台】，选择【终端】，输入：
```sh
sudo spctl  --master-disable
```
接着打开【系统偏好设置】，选择【安全性与隐私】，选择【通用】，可以看到【任何来源】已经选定。

![image](https://user-images.githubusercontent.com/29914689/199900019-311ca52f-72da-4142-b3eb-1d01b46d2216.png)

如果发现还是显示“已损坏，无法打开。 您应该将它移到废纸篓”，不急，接下来用这种方法：
在终端粘贴复制输入命令（注意最后有一个空格）：

```sh
sudo xattr -r -d com.apple.quarantine 
```

然后打开 “访达”（Finder）进入 “应用程序” 目录，找到该软件图标，将图标拖到刚才的终端窗口里面，会得到如下组合(如图所示)：

```sh
sudo xattr -r -d com.apple.quarantine /Applications/Fiddler\ Everywhere.app
```
回到终端窗口按回车，输入系统密码回车即可。

![image](https://user-images.githubusercontent.com/29914689/199901947-ff1060e5-803f-4f8f-a21e-53779b12bd73.png)

接着重新打开安装软件，就可以正常安装了。

**Comment by rich1e** [comment]
以上 Crack 方式可能存在问题，还需要关闭 `Fiddler Everywhere` 自动更新。

> 自动更新的代码在 /Applications/Fiddler\ Everywhere.app/Contents/Resources/app/out/main.js 中。

在 `main.js` 中搜索 `Check for Updates...`，找到其对应的函数是 `checkForUpdatesAndNotify`.

![image](https://user-images.githubusercontent.com/29914689/199936683-2c1cb75e-8e24-4fed-a1eb-e4be67c8a9df.png)

修改 `checkForUpdatesAndNotify` 函数，添加 `return !0;`，这样后面的逻辑就不会执行了，即关闭了自动更新。

![image](https://user-images.githubusercontent.com/29914689/199936467-d53c6219-3594-4525-a8ef-aa3fec0922d3.png)

参考：
> https://www.52pojie.cn/forum.php?mod=viewthread&tid=1679708

**Comment by heyanpeng** [comment]
> 首先需要说明一点，crack 文件不是通过自己编译得到。 反反复复折腾了很久，只差编译这最后一步，最终还是妥协了。
> 
> > 退回到 v3.4.0 的版本，再 Crack。
> 
> 目前可以正常使用（没有 `Trial` 标志），似乎更新了，仍然可以使用（截图可以看到，Crack 后的版本是 v3.4.2）。
> 
> 1.先安装 fiddler everywhere 3.4.0； 2.打开 fiddler everywhere，选择试用； 3.关闭 fiddler everywhere，替换 crack 文件； 4.再次打开，没有试用的标志，完美使用；
> 
> > 操作步骤必须按照顺序，否则会 crack 失败！
> 
> ![](https://user-images.githubusercontent.com/29914689/199898464-c145d3aa-668d-47a2-979e-4576ce93dac5.png)
> 
> ![](https://user-images.githubusercontent.com/29914689/199898374-25d01fa9-5e2e-446f-93b6-14c1ed53f8ce.png)
> 
> [crack 文件](https://pan.iculture.cc/s/3bgAIP)，**只对应 `v3.4.0 for mac` 版本。**
> 
> ## FQA
> ### 如果出现了please wait，可能是因为先crack后联网。
> > 卸载 fiddler everywhere，按照上述步骤重新安装就可以解决。
> 
> 类似问题：
> 
> * [替换文件后停留在 Please wait... 界面 #9](https://github.com/msojocs/fiddler-everywhere-crack/issues/9)
> * [修改之后卡在登录页面 #3](https://github.com/msojocs/fiddler-everywhere-crack/issues/3)
> 
> ### 如果打开 fiddler everywhere 时遇到“已损坏，无法打开。 您应该将它移到废纸篓”的问题。
> 打开【启动台】，选择【终端】，输入：
> 
> ```shell
> sudo spctl  --master-disable
> ```
> 
> 接着打开【系统偏好设置】，选择【安全性与隐私】，选择【通用】，可以看到【任何来源】已经选定。
> 
> ![image](https://user-images.githubusercontent.com/29914689/199900019-311ca52f-72da-4142-b3eb-1d01b46d2216.png)
> 
> ### 如果发现还是显示“已损坏，无法打开。 您应该将它移到废纸篓”。
> 不急，接下来用这种方法：在终端粘贴复制输入命令（注意最后有一个空格）：
> 
> ```shell
> sudo xattr -r -d com.apple.quarantine 
> ```
> 
> 然后打开 “访达”（Finder）进入 “应用程序” 目录，找到该软件图标，将图标拖到刚才的终端窗口里面，会得到如下组合(如图所示)：
> 
> ```shell
> sudo xattr -r -d com.apple.quarantine /Applications/Fiddler\ Everywhere.app
> ```
> 
> 回到终端窗口按回车，输入系统密码回车即可。
> 
> ![image](https://user-images.githubusercontent.com/29914689/199901947-ff1060e5-803f-4f8f-a21e-53779b12bd73.png)
> 
> 接着重新打开安装软件，就可以正常安装了。

亲测，按照此方法v3.4.2在过期后能有效破解

**Comment by CoolAnsonT** [comment]
请问近期会有V4.0.1 Mac M1 arm64版本的crack文件更新吗？请问能否上传一份？谢谢！ @msojocs

**Comment by msojocs** [comment]
> 请问近期会有V4.0.1 Mac M1 arm64版本的crack文件更新吗？请问能否上传一份？谢谢！ @msojocs

我没有mac,所以不会提供的，仓库里面是别人pr的。

**Comment by aTenb** [comment]
求4.0.1版大佬PR

**Comment by heyanpeng** [comment]
> 首先需要说明一点，crack 文件不是通过自己编译得到。 反反复复折腾了很久，只差编译这最后一步，最终还是妥协了。
> 
> > 退回到 v3.4.0 的版本，再 Crack。
> 
> 目前可以正常使用（没有 `Trial` 标志），似乎更新了，仍然可以使用（截图可以看到，Crack 后的版本是 v3.4.2）。
> 
> 1.先安装 fiddler everywhere 3.4.0； 2.打开 fiddler everywhere，选择试用； 3.关闭 fiddler everywhere，替换 crack 文件； 4.再次打开，没有试用的标志，完美使用；
> 
> > 操作步骤必须按照顺序，否则会 crack 失败！
> 
> ![](https://user-images.githubusercontent.com/29914689/199898464-c145d3aa-668d-47a2-979e-4576ce93dac5.png)
> 
> ![](https://user-images.githubusercontent.com/29914689/199898374-25d01fa9-5e2e-446f-93b6-14c1ed53f8ce.png)
> 
> [crack 文件](https://pan.iculture.cc/s/3bgAIP)，**只对应 `v3.4.0 for mac` 版本。**
> 
> ## FQA
> ### 如果出现了please wait，可能是因为先crack后联网。
> > 卸载 fiddler everywhere，按照上述步骤重新安装就可以解决。
> 
> 类似问题：
> 
> * [替换文件后停留在 Please wait... 界面 #9](https://github.com/msojocs/fiddler-everywhere-enhance/issues/9)
> * [修改之后卡在登录页面 #3](https://github.com/msojocs/fiddler-everywhere-enhance/issues/3)
> 
> ### 如果打开 fiddler everywhere 时遇到“已损坏，无法打开。 您应该将它移到废纸篓”的问题。
> 打开【启动台】，选择【终端】，输入：
> 
> ```shell
> sudo spctl  --master-disable
> ```
> 
> 接着打开【系统偏好设置】，选择【安全性与隐私】，选择【通用】，可以看到【任何来源】已经选定。
> 
> ![image](https://user-images.githubusercontent.com/29914689/199900019-311ca52f-72da-4142-b3eb-1d01b46d2216.png)
> 
> ### 如果发现还是显示“已损坏，无法打开。 您应该将它移到废纸篓”。
> 不急，接下来用这种方法：在终端粘贴复制输入命令（注意最后有一个空格）：
> 
> ```shell
> sudo xattr -r -d com.apple.quarantine 
> ```
> 
> 然后打开 “访达”（Finder）进入 “应用程序” 目录，找到该软件图标，将图标拖到刚才的终端窗口里面，会得到如下组合(如图所示)：
> 
> ```shell
> sudo xattr -r -d com.apple.quarantine /Applications/Fiddler\ Everywhere.app
> ```
> 
> 回到终端窗口按回车，输入系统密码回车即可。
> 
> ![image](https://user-images.githubusercontent.com/29914689/199901947-ff1060e5-803f-4f8f-a21e-53779b12bd73.png)
> 
> 接着重新打开安装软件，就可以正常安装了。

V4.0.1 Mac M1 arm64大佬能更新一下吗

**Comment by aTenb** [comment]
https://github.com/aTenb/fiddler-everywhere-enhance/tree/master/4.0.1-mac 已经PR
